### ISSUE TITLE
Questguide with questie 

### ISSUE THREAD

**Issue by malloot** [AeroScripts/QuestieDev#105]
I'd like to setup a project to make James vanilla leveling guide into an addon that works with the crazy arrow from Questie. I however have no experience with writing a addon so initially just set out to rewrite the Vanillaguide addon for alliance to James guide (Brian Kops is horrible). However it would be a shame not to use the information Questie provides in terms of locations and spawnpoints.

How would i be able to hook into Questie from Vanillaguide so i can say point arrow to quest x or pickup quest y?

Another option is that the guide making structure is build into Questie and i can rewrite the guides into Questie using a given set of tools.

**Comment by Schaka** [comment]
https://github.com/AeroScripts/QuestieDev/blob/master/Questie/QuestieArrow.lua

Take a look into SetCrazyArrow(point, title, dist)

The point table will need to contain the following properties:
point.c = continent the coordinate is on
point.z = zone the coordinate is on
point.x = x
point.y = y

It's a global function you can call from within your own addon. It will show the arrow on screen (given that you have Questie installed). You can't JUST export our arrow class - though technically you could - because it depends on Astrolabe, which we use for all distance/angle calculations.

**Comment by malloot** [comment]
Hey thnx for your fast response!

That would still make me have to search the location for every quest pickup and return and manually add the locations into the guide. That is exactly what i wanted to avoid by using Questie. Basically i would like to be able to do what Shift clicking a quest in the Questie quest tracker window does. 
Something like
SetCrazyArrow("questid")

**Comment by Schaka** [comment]
There are no questids. Assuming the quest is actually in the log, you can call SetArrowObjective(hash) whereas hash is our internal QuestHash as returned by Questie:getQuestHash(hash)

https://github.com/AeroScripts/QuestieDev/blob/master/Questie/Questie.lua

**Comment by malloot** [comment]
Nothing needs to be automated though, its mostly about not having to alt tab to look at steps. 

Basically the easiest way to make this would be to just write a form of pickup quest x and having all the data in terms of locations come from Questie.  But as far as i understand Questie is not really made to work that way. 
Even if nothing is automated Vanillaguide is not useless at all, finishing quests is not the part that is especially hard in vanilla and like you say Questie already helps with that. 
It is the obtaining a good amount of quests in a zone with the least of amount of travel that costs allot of time if not done properly. 

I guess i will just rewrite vanilla guide to James old version guides for now.
