### ISSUE TITLE
A number of breadcrumb quests still not working properly

### ISSUE THREAD

**Issue by Ben1220** [AeroScripts/QuestieDev#1060]
Hi, 

I'm not sure what the official plan is for "breadcrumb" quests (those which send you to another NPC and seem to be easy to miss permanently by speaking directly to the NPC first).  However, it appears from other reports that they are intended to be removed from the "available quests" if they are missed?  

See Issue https://github.com/AeroScripts/QuestieDev/issues/881

I have found three of these quests which are still showing up either on the map, or in the quests by zone "available quest" list despite being impossible to complete if you miss them.  

1. Senirs Observations (as also noted by the linked issue 881)
2. Eagan Peltskinner  (Elwynn Forest)
3. Jungle Secrets (STV)

**Comment by BreakBB** [comment]
The quests by zone tab is currently working on it's own and really needs some improvements. Could you tell which quests are shown on the map and which are listed for "Quests by Zone"?

1. Should not show up on the map
2. Has been fixed with a971b99b00732ceff6347d9cbfa51c08356e67a9 and will be in the next release (thanks for the report!)
3. Are you sure you've already completed the quest? Have a look at #869

**Comment by Ben1220** [comment]
Thanks for the response.  

Please disregard Jungle Secrets, I was mistaken about this one, it isn't actually a breadcrumb quest it is only accessible for a short period of time once an hour or so.    

As to the other two (Senirs observations and Eagan Peltskinner).  Both do not show up on the map but do show up as available on the quest by zone tab.  

Senir's observation used to also appear on the map but has been fixed as of the last few releases (I assume thanks to issue #881 bringing it to attention.)  

I will let you know if I come across any other quests like this.
