### ISSUE TITLE
The love potion does not show objectives

### ISSUE THREAD

**Issue by Magissia** [AeroScripts/QuestieDev#1136]
## Description

Objectives in azshara are not shown on the map

## Wowhead link

https://classic.wowhead.com/quest=4201/the-love-potion

## Questie version

4.1.1

**Comment by BreakBB** [comment]
Thanks for the report. I could find out that the place to fill the vial wasn't marked, but this is fixed with 10b2592a429ec5bb9c02930e2cff648b1cbee3fb.

For Azshara I couldn't find any issue. I'll ask here again. Are you using a client language different to English? We had an issue with quests having multiple objectives

**Comment by Magissia** [comment]
Yes

**Comment by BreakBB** [comment]
Then this is related to #1071 and fixed with the release of v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
