### ISSUE TITLE
Pamela's Doll

### ISSUE THREAD

**Issue by ssateneth** [AeroScripts/QuestieDev#1148]
## Description

Quest object doesnt show complete when you assemble the doll. Force reloading questie after you assemble the doll shows it complete. Also the gears for the doll pieces remain until you turn in the quest

## Wowhead link

https://classic.wowhead.com/quest=5149/pamelas-doll

## Questie version

4.1.1

**Comment by BreakBB** [comment]
Items "created" by the user (along with items received by mail/trade) aren't tracked correctly yet. But we already have a working solution on our dev branch which we need to test more to solve such issues.

I've added a missing item for this with 1c8ba0ad2b6da6b0179d1db2846fc3a7612efe72

And the gears remain for now since those are just "sub objectives". We will change this in a future update once we're sure the changes stated above work correctly. Thanks for your report 😃
