### ISSUE TITLE
Questie markers displayed in wrong area (Question)

### ISSUE THREAD

**Issue by Inspired2150** [AeroScripts/QuestieDev#117]
![questie issue](https://cloud.githubusercontent.com/assets/12717767/7941676/8b8f0ad4-0961-11e5-9133-efe8a85b53ae.png)
Hello!

I have been using Questie for quite some time, however I have ran into an issue.
I have installed a German client and copied WTF and Interface options over.

Everything is fine except for Questie. As you can see, it displays quest  locations incorrectly.

I have also tried completely deleting the WTF folder, and it still does that.

Does Questie even work with other locales?
Thank you.

P.S. What's strange is the quests than I have not yet taken are displayed where they should (the exclamation marks), but quest goals are not. :(

**Comment by Schaka** [comment]
This is due to you using the German client, which has incorrect offsets. We do not have the correct offsets and are unsure how to collect them. The AvailableQuests use a completely different system, as they are exported directly from Mangos and can be translated into ingame coordinates flawlessly. 

We decided a while ago, that we will not support other client localizations. Therefore I am closing this.
