### ISSUE TITLE
Add data to search results: Quest status / Item Correlation

### ISSUE THREAD

**Issue by dever23b** [AeroScripts/QuestieDev#1188]
## Description
I really like that there's a search feature; however, the results leave room for desire.  I often find that the search tool is effectively useless, because the results contain minimal if any data.  Instead, I have to use the Quests by Zone tab to drill down and manually find the quest I need information on.  The search results lack information that Questie seems to already be aware of, which gives hope that including more data thereto wouldn't be a huge feat (compare the data returned from a search result to the data available on the Quests by Zone tab for the same quest).

Request 1: add the completion status to the search result information on a given quest query.  The #1 reason I look up a quest by name in Questie (via search or manually finding it in the By Zone tab) is to figure out whether I've completed it yet or if, perhaps, it's part of a line of quests and I haven't completed a pre-requisite.  Questie clearly knows which quests I've completed, but it's tedious to actually extract that information.  

Request 2: display the same data in a search result for a quest as is contained on the Quests by Zone tab.  When you manually drill down and find a quest through the By Zone tab, there is an abundance of helpful information.  Unfortunately, none of it seems to be currently available if we search for a specific quest rather than browsing.  If this is not practical, at a minimum, could the Continent & Zone be included in the search result to make it easier to switch tabs and find more detail on the quest query?

Request 3: for item search results, include data about the item(s).  Currently, the resultset just returns a list of matching items.  Confirmation that the item exists in-game is marginally helpful, but could we get some information about the item?  At a minimum, could the result list of items be presented as item links that we could hover over and/or click on to see the standard item detail tooltip?  I'm not sure if this information is available in the API, but if it's possible, it'd be really (really) helpful if the item search could correlate quest items to their corresponding quest.  This would be helpful for quest items that do not obviously indicate which quest they are for (as an example: Fizzle Brassbolts' Letter, which is a quest item that doesn't get removed upon completion of its quest).

Thanks for the great addon!

**Comment by Muehe** [comment]
Yeah the search feature is pretty unfinished, sorry for that. Got side-tracked with bugs and other features. 

As for your requests:

1. Finished status on quests

Should be pretty easy to add.

2. Different pages between search and "by zone"  

The page that is currently in the search is very WIP. Before I started working on it it used the same page shown in the "by zone" view. I wanted to have different pages because I intended to extend the functionality without influencing the working of the by zone view. Gonna prioritise this work after I finished the feature I'm currently working on, which is kind of related anyway (marking arbitrary spawns on the map, even if they aren't related to a quest).

3. Item search results
    * item links
    * tooltips  

All of this is possible, just wasn't added yet. The last work I did was focused on showing results for objects and items, which were still missing. Then I started redoing, or for objects/items creating, the pages. NPCs are still pretty bare too.

**Comment by hijxf** [comment]
would love to see completed quests! thanks.

**Comment by Muehe** [comment]
Completed status is now shown in the search, both on the list and the details frame:

![](https://cdn.discordapp.com/attachments/263040777658171392/643854593087897620/unknown.png)

**Comment by dever23b** [comment]
Awesome! Thanks so much!

**Comment by hijxf** [comment]
Nice! Thanks!

**Comment by BreakBB** [comment]
The search should also show if you are currently on the quest you found.

**Comment by Gogo1951** [comment]
Hey @dever23b ,

This looks to be completed. If you care to re-open that's fine. Just trying to clear out the board.

If you do have to re-open, please create separate tickets for separate requests. Thanks!
