### ISSUE TITLE
Group map markers

### ISSUE THREAD

**Issue by teodias** [AeroScripts/QuestieDev#1229]
Would be cool having map markers for the quest locations of the group members.

So I could see where my mates have to go even if i already completed the quest.

Also seeing which queste my mates have even if I don't have that quest anymore.

I understand this will only work if both/all have Questie running to communicate, thats OK.
The most ppl I met were using Questie ;)

**Comment by Gogo1951** [comment]
**From my duplicate issue:**

As someone who frequently quests with others, I love that you have added the quest items to the tool tip. Possible to also display those items on the map / minimap with a little icon or * next to it, indicating that it's for your friends?

Should only show in a 5-man group, not a raid. Since you can't get quests done in a raid anyway. (=

**Comment by AeroScripts** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.

**Comment by mook06** [comment]
This would be an awesome feature atm!
