### ISSUE TITLE
Quest #3374 - The Essence of Eranikus

### ISSUE THREAD

**Issue by bitingsock** [AeroScripts/QuestieDev#1233]
## Description
This is an indirect followup to https://classic.wowhead.com/quest=3373/the-essence-of-eranikus and does not show on the map. It is a bit confusing as it requires some dialog to receive the item that actually starts the quest. 

## Wowhead link
https://classic.wowhead.com/quest=3374/the-essence-of-eranikus
https://classic.wowhead.com/quest=3512/in-eranikus-own-words

## Screenshots
![image](https://user-images.githubusercontent.com/6302101/66266378-308d5900-e7d9-11e9-94eb-4277757a7a08.png)

## Questie version
v4.1.1

**Comment by BreakBB** [comment]
Quests that are started by an item are not shown on the map yet, because we haven't figured out a good way. Most of those items are randomly dropped by a lot of mobs and we don't want to flood the map with icons for them.

But this is actually a quest where we should easily be able to add the NPC as starting point
