### ISSUE TITLE
Arcane Runes/Signal for Pickup (3449/3451)

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1256]
## Description
The quest "Signal for Pickup" doesn't disappear from the map once you have completed "Arcane Runes".

## Wowhead link
https://classic.wowhead.com/quest=3449/arcane-runes
https://classic.wowhead.com/quest=3451/signal-for-pickup

## Screenshots
![](https://i.imgur.com/AUuMPEm.jpg)

## Questie version
4.1.2

**Comment by Djfe** [comment]
also happening in 4.1.2

**Comment by Djfe** [comment]
#1131

**Comment by Djfe** [comment]
also the quest icon is still yellow instead of blue and I can't reopen the old issue

**Comment by Muehe** [comment]
The fix that closed 1131 was not included in 4.1.2, but it will be in the next release. We had a bit of a hard time writing the changelog because it included >100 commits. Will be the same for the next release, so it will probably be on Github sooner than it will on Curse/Twitch.

As for the topic at hand, probably a missing parent quest relation, will look into it.

**Comment by Muehe** [comment]
Hmm, looks like that was already fixed pursuant to #1008 and as you can see on [the commit](https://github.com/AeroScripts/QuestieDev/commit/bdb41df1121ef3536859b8408d7dff7d237ce931) it should be included since 4.1.1. Are you sure you updated correctly and don't have multiple Questie folders in your addons?

**Comment by BreakBB** [comment]
Fixed with aff14e8f2d8e97affe9d95a8fe275f38dcb49c17 and aff14e8f2d8e97affe9d95a8fe275f38dcb49c17
