### ISSUE TITLE
ungoro soil isn't tracked on mobs

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1257]
## Description
Questie doesn't mark mob's at ungoro even though they drop ungoro soil.
I don't want any additional markers on the map, just the info on the mobs' nameplates :)

## Wowhead link
https://classic.wowhead.com/object=157936/ungoro-dirt-pile
https://classic.wowhead.com/item=11018/ungoro-soil

## Questie version
4.1.2

**Comment by Muehe** [comment]
The NPC drops have intentionally been disabled in the database, because they basically just paint the whole zone with bags. This also had to do with performance concerns, but the improvements contained in 4.1.2 might enable us to show those notes (and others like ore veins/herbs) again. No promises though.

In the meantime, if you want to see the notes, you can manually remove line 649 (in the latest commit) from the file `Database/corrections.lua`:

```diff
-    [11018] = {"Un\'Goro Soil",{4496,3761,3764},{},{157936}},
```

Note though that this change will be overwritten when you update Questie.

**Comment by Djfe** [comment]
makes sense, but I don't want them to show up on the map. Just the loot bag icon next to the mob, if I select it. and the info in the box bottom-right, when I hover over the mob.

**Comment by Djfe** [comment]
I see ^^

**Comment by BreakBB** [comment]
@Djfe If you want to see an option for this please create a feature request. I am closing this for now since this issue is fixed.
