### ISSUE TITLE
Northshire - "A quest within" available quest won't go away

### ISSUE THREAD

**Issue by frozenreddy** [AeroScripts/QuestieDev#126]
Questie keeps telling me that Deputy Willem is still offering A Quest Within even though he is not. Same is true for Rest and Relaxation. Any way to manually remove !s?

**Comment by Schaka** [comment]
There is no way to manually remove them. The reason for this could be either that you are using an addon that modifies the quest text at a point where we can't safely hook the name (EQL3, for example) or because your server supplies a quest text different from the one in our database. This can lead to discrepancies that are close to impossible to fix (and the above issue).

You will have to deal with it. Removing AvailableQuest notes by rightclicking on them (or something along those lines) is planned for future releases. That being said, development is at a halt right now.
