### ISSUE TITLE
Improve DBM HUD

### ISSUE THREAD

**Issue by Dogasawi** [AeroScripts/QuestieDev#1310]
## Bug description

the ! for quests that should be on minimap seems instead to be rotating around the center of my actual screen. in otherwords they are everywhere

only solution was to disable questie  (immediately solved issue)

**Comment by drejjmit** [comment]
That is the new DBM HUD feature.
It helps to navigate to available quests and quest objectives.
There is a new "DBM" tab in the config if you want to change it

**Comment by Dogasawi** [comment]
YEAH thank you i discovered issue solution as well.  SUGGESTION:

MAKE IT REQUIRE TO BE TURNED ON, MAKE IT OFF BY DEFAULT PLEASE.  TY TY TY

**Comment by crisX10** [comment]
Same here. Pls not as default. Thank you very much for questie.

**Comment by oNIenSis** [comment]
This is a good idea but the implementation needs a bit of a rethink. Needs more subtle indicators on the side of the screen - perhaps a fixed arc that glows with an intensity that depends upon quest proximity. I'm no designer - but here's a suggestion (the onscreen ! indicators would be replaced with the arc). 

![WoWScrnShot_101519_120105_suggested](https://user-images.githubusercontent.com/4584269/66793123-bdf24b00-ef47-11e9-8b8c-dd3c32f6d5f1.png)

The main thing would be to have it in a fixed distance from the character rather than moving further away (very distracting), and replace with something subtler than the indicators.

An alternative (easier) option would be to have the indicators arranged on an arc with a size reflecting the distance away. The indicators would move around the arc as you move, but change in size rather moving further away from the character.

![WoWScrnShot_101519_120105_suggested_1](https://user-images.githubusercontent.com/4584269/66793143-cba7d080-ef47-11e9-853e-8d355bdf5946.png)

I'd suggest making them slightly transparent as well or at least having transparency option.

**Comment by MysticalOS** [comment]
I don't think showing the arc is really doable, and the icons use literal world coords so distance they are drawn wouldn't really be changable either. the suggestion I had, was maybe reel in the default zoom. by default it shows all icons within 100 yards, but maybe you can try 40 or 50 yards. and maybe diff icon sizes. I personally liked seeing 100 yards ahead of me but some might rathor it only show as much as minimap does instead?

**Comment by Takktics** [comment]
Thanks for answering this, I thought the last update had broken something. This definitely doesn't seem like a feature, the icons don't even line up with the correct objects when you get near them. At the very least this should be turned off by default.

**Comment by MysticalOS** [comment]
I have no idea how it works these days, since they added all kinds of changes like clustering etc. DBM hud would still show icons where they are in database, not where they get clustered so I imagine they might not always match up anymore if I had to guess. But since DBM hud aims to put icons in real world positions, that's probably right way to do it, despite clustering. I have no time to look at this any time soon though. However, with how wildly unpopular feature was and how few use it, it's not a very high priority either. I'll fix it if it's actually broken but if it's just working way it always did, but doesn't quite align with clustering, thats probably fine.

**Comment by TimurBorn** [comment]
The DBM feature seems quite useful, still trying it out. What I noticed, though, is relatively high CPU load of DBM's core module when Questie's DBM hud is active. CPU load is higher than Elvui, which is among the most demanding addons on my system, even more than Questi itself.

**Comment by MysticalOS** [comment]
The cpu usage is actually about as low as it's gonna get without compromising the hud and it's only outdoor in world so it's fine, soon as you enter an instance it goes to 0. The hud's just calculating real world position of every icon on entire continent at all times. not just current zone but entire continent you're on. cpu usage could be lowered more by reducing it now to only zone but then it'd break near zone borders where objectives are on both sides, or lose some of the cool smoothness on taxis, so i think it's fine as is.

Mainly though, it comes down to fact that i've suspended all development on feature. present and future. it had poor reception and my time is limitted.

**Comment by TimurBorn** [comment]
Well, I quite like the function. Absolutely speaking the CPU load is not high, but relatively DBM core usually sit on #2 for CPU load in a long list of running addons.

Unfortunately CPU load does not drop indoors, just stays the same as outside. I did not check instances yet, but I assume that it works the way you described.

**Comment by Gogo1951** [comment]
Will be replacing HUD with Tom Tom in BC. #2502
