### ISSUE TITLE
Questie minimap icon remains attached to mouse movement

### ISSUE THREAD

**Issue by kaos89** [AeroScripts/QuestieDev#1352]
## Bug description
As object QuestieMinimap button stay attached to the mouse pointer when I try to move it on minimap.
I have ElvUI and ProjectAzilroka. In the previous version this bug didn't happen.

## Questie version
 v4.3.0
 37acad5

**Comment by BreakBB** [comment]
@kaos89 Can you check if this still happens with the latest version of Questie?

**Comment by kaos89** [comment]
ElvUI + Project Azilroka
still happening, minimap button stay anchored to mouse movement

 Questie Version

v5.0.1
 dc428f5

**Comment by BreakBB** [comment]
@kaos89 Is this still a problem? Or could you explain how to reproduce this? I can't make it happen.

**Comment by BreakBB** [comment]
@kaos89 We were finally able to test this and also to reproduce it.

If you're using just ElvUI everything is working fine, but Project Azilroka is supposed to remove the icons from the minimap and add them to some kind of "minimap icon bar". So you shouldn't see any icons on the minimap.

If you do, then you should contact the Project Azilroka devs since Questie is using the Ace library as addons are supposed to.
