### ISSUE TITLE
Make Zone selector dropdown list alphabetical order for Quests by Zone at Journey

### ISSUE THREAD

**Issue by arphox** [AeroScripts/QuestieDev#1357]
## Description
Go to **Journey**, then click the **Quests by Zone** tab.
Select any continent, and the right dropdown list becomes active.
I would like that dropdown list to be in **alphabetical order** to be able to find a zone faster.

Screenshot of current state:
![kép](https://user-images.githubusercontent.com/17320094/67125321-d470fe80-f1f4-11e9-89d1-97cbd860e6b6.png)

_(Also I am interested in implementing this, if you have any idea how to do it, please let me know and I try to implement it by myself.)_

**Comment by Spencer0** [comment]
I just saw your comment about wanting to know how to implement this, i submitted a pull request for this feature (https://github.com/AeroScripts/QuestieDev/pull/1382) so i can speak a little bit to it. 

Since we wanted to sort a collection on screen, i just went over to stack overflow and searched for sorting lua tables. From there, i looked into how that SetList function works from ACE GUI. These two links were all i really needed. 

https://stackoverflow.com/questions/2038418/associatively-sorting-a-table-by-value-in-lua

https://www.wowace.com/projects/ace3/pages/ace-gui-3-0-widgets
