### ISSUE TITLE
offer to provide gatherlite db for coordinates of quest items

### ISSUE THREAD

**Issue by Djfe** [AeroScripts/QuestieDev#1359]
Gatherlite doesn't add fish and treasure to their predefined database, yet.
But I could provide mine.
Would that help?

https://gatherlite.labcake.org/

#1258 questie does have plenty of spots for un'goro soil and crystals for example but definitely not all of them. (as an example)
And my db would also include quest items for other quests.
I only started using gatherlite after lvl 40 or 50 or so.
But my db also contains data from my guild and people from groups I was in.

**Comment by Djfe** [comment]
with this you could easily see which crystals dropped where etc.

the items names are english or german depending on the client's language

**Comment by BreakBB** [comment]
It should be easy to add all those spots to our database if you provide them. Adding a Pull Request for it is easy as well :)
I have to note though that we combine some notes as "clusters" in some places and don't show every spot we have in our db.

**Comment by BreakBB** [comment]
This issue is being closed because the level of development effort required is substantial and doesn't line up with the number of requests we've received from current users. The issue will remain as an archived issue on GitHub, and should you ever want to do the development work you can reopen it and submit a pull request with your work. Sorry your idea didn't make the cut this time around, but please keep the suggestions coming and thanks for taking an interest in improving Questie!
