### ISSUE TITLE
2.0.13 renaming of AddOn resets WTF saved variables

### ISSUE THREAD

**Issue by zr00130** [AeroScripts/QuestieDev#142]
Due to the rename from Questie to !Questie the saved variables per character were no longer loaded. 

I was able to rename my WTF\Account\\\<account\>\\\<server\>\\\<character\>\SavedVariables "Questie.lua" to "!Questie.lua" and it seemed to have worked fine.

Is there any issues with this renaming? I also assumed we needed to remove the Questie and !QuestieCompatability addon folders in favor of the new !Questie folder.

**Comment by AeroScripts** [comment]
Yes, I should have been more clear. I wasn't expecting it to affect savedvariables. The reason for the change is that multiple people had issues with broken installs when forgetting to copy in QuestieCompatibility aswell.

**Comment by howardkent** [comment]
The problem anzz1 has faced with forgotten quests is due to neglecting to rename the Questie.lua to !Questie.lua in the character SavedVariables folder, and to a lesser extent rename the Account SavedVariables !QuestieCompatibility.lua file to !Questie.lua (and deleting the !QuestieCompatibility.lua file).

As we all know, generally addons use the .lua the same name as the folder.

**Comment by Logonz** [comment]
Hopefully in our core rewrite this will never ever be a issue again.
