### ISSUE TITLE
Update 2.0.13 breaks compatibility with some plugins

### ISSUE THREAD

**Issue by anzz1** [AeroScripts/QuestieDev#143]
Update 2.0.13, the combining of the !QuestieCompatibility and Questie to !Questie breaks compatibility with some plugins. I think it's breaks the compatibility with Extended Quest Log.
After updating, Questie forgets which quests I have done and shows all as undone. Also it will track all quests in the game window, and quests can't be tracked/untracked anymore by shift+clicking them in the quest log. 2.0.12 works fine.

My plugins list:
Extended Quest Log (EQL3)
Cartographer
CEnemyCastBar
EquipCompare
OneBag
OneBank
OneView
OneRing
TNE_LowHealthWarning
WHDB

Link to my addons for testing: http://kug.us.to/files/WoW_Vanilla_1.12.1_Addons.rar

**Comment by AeroScripts** [comment]
Thanks ill take a look into it, didn't have a chance to test it with other mods. I personally wanted to keep them separate anyway but multiple people had broken installs when they forgot to copy QuestieCompatibility

**Comment by howardkent** [comment]
The problem anzz1 has faced with forgotten quests is due to neglecting to rename the Questie.lua to !Questie.lua in the character SavedVariables folder, and to a lesser extent rename the Account SavedVariables !QuestieCompatibility.lua file to !Questie.lua (and deleting the !questiecompatibility file).

He is on point about the tracker. I can't comment on the incompatibilities, I only noticed an odd behaviour with FishingBuddy, which I disabled and Questie worked fine (albeit without the tracker working well).
