### ISSUE TITLE
Missing Diplomat step 3 is missing a quest marker for the mage location

### ISSUE THREAD

**Issue by fireboy92k** [AeroScripts/QuestieDev#1490]
## Description

Quest 3 in The Missing Diplomat series directs you to visit the first tower outside of Theramore.  There should be a quest marker directing the player to that location since there is no quest completion '?' that shows up until you enter the tower and the mage appears.

## Wowhead link

https://classic.wowhead.com/quest=1265/the-missing-diplomat

## Questie version

v5.0.1

**Comment by BreakBB** [comment]
@fireboy92k Thanks for this report. I had a look at our data and I only found that we've had more than 1 location marked for this quest:

`{"Sentry Point explored",{[15]={{59.92,40.9},},[17]={{66.55,75.15},},}},`

The latter one directs to The Barrens which doesn't make much sense. I removed it already.

Since we did some cleanup with the latest release I would like you to update Questie to v5.1.0 👍
