### ISSUE TITLE
"Hide Questie" button on the map doesn't work

### ISSUE THREAD

**Issue by wodim** [AeroScripts/QuestieDev#1510]
v5.1.0, when I click the "Hide Questie" icon that's shown above the map I get this error:

```
Message: [string "Questie_Toggle:OnClick"]:1: attempt to index global 'QuestieQuest' (a nil value)
Time: Fri Nov  8 20:17:00 2019
Count: 1
Stack: [string "Questie_Toggle:OnClick"]:1: attempt to index global 'QuestieQuest' (a nil value)
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = Questie_Toggle {
 0 = <userdata>
 Text = Questie_ToggleText {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 Left = <unnamed> {
 }
}
button = "LeftButton"
down = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'QuestieQuest' (a nil value)"
```

No other addons are loaded.

**Comment by BreakBB** [comment]
Thanks for your report! There was indeed a problem with the button which has already been fixed with ff44a21af77e1ffe7f49301582e901f17baa70cd

If you're relying on this button and don't want to wait till the next release you can place the file of the ZIP below into your `Questie` folder replacing the existing `embeds.xml`


[embeds.zip](https://github.com/AeroScripts/QuestieDev/files/3827330/embeds.zip)
