### ISSUE TITLE
Questie 5.1.0: Alliance-Quests show up for Horde Character

### ISSUE THREAD

**Issue by Mankriks-Neighbor** [AeroScripts/QuestieDev#1520]
I have several Quests displayed in "Quests by Zone" which are not obtainable by my Lvl 39 Orc Hunter.
They seem to be Alliance-only Quests.

Available in Ironforge (5)
Quest ID: 687 Theldurin the Lost
Quest ID: 737 Forbidden knowledge
Quest ID: 3645 Membership Card renewal
Quest ID: 4661 Testing for Corruption - Felwood
Quest ID: 4561 Testing for Impurities - Un'Goro

Available in Redridge Mountains (1)
Quest ID: 3741 Hillary's Necklace
edit: Doable as Horde

Available in Stormwind (1)
Quest ID: 5050 Good Luck Charm

Available in Teldrassil (1)
Quest ID: 1581 Elixir for the Bladeleafs

**Comment by drejjmit** [comment]
Available in Ironforge (5)
Quest ID: 687 Theldurin the Lost: Shows up in IF since it has the same questid as the horde version that's picked up from Zaruk in Arathi Highlands. YOu should see it under Arathi as well.
Quest ID: 737 Forbidden knowledge: Same here. Picked up from Keeper Bel'dugur in Undercity. Should also be under Undercity.
Quest ID: 3645 Membership Card renewal: Picked up from neutral npc Oglethorpe Obnoticus in Booty Bay for Gnomish Engineers.
Quest ID: 4661 Testing for Corruption - Felwood: No idea how that can show up in IF. It's a quest in Undercity.
Quest ID: 4561 Testing for Impurities - Un'Goro: Same. Undercity.

Available in Redridge Mountains (1)
Quest ID: 3741 Hillary's Necklace: Hordes can actually do this quest. Go see for yourself.

Available in Stormwind (1)
Quest ID: 5050 Good Luck Charm: Same quest id as the Horde version. Should show up under Undercity as well.

Available in Teldrassil (1)
Quest ID: 1581 Elixir for the Bladeleafs. This quest needs to be tagged as Alliance only.

Some code is needed to hide those not only as quest markers but in the Journey as well.

**Comment by Mankriks-Neighbor** [comment]
Hillary's Necklace is doable as Horde? Don't you need to talk to the Girl?

**Comment by drejjmit** [comment]
The girl doesn't have a faction tag.

**Comment by Mankriks-Neighbor** [comment]
Looked it up on Wowhead, you're right.

**Comment by BreakBB** [comment]
@Mankriks-Neighbor Thanks for your report! We've had a look into our data and we've missed a check for NPCs that are friendly (hiding most of the quests in with one small fix).

Some others really had a wrong faction tag. Fixed your quests 👍
