### ISSUE TITLE
Wrong language display in tooltip and questie tracker(Chinese Client)

### ISSUE THREAD

**Issue by SqiChiu** [AeroScripts/QuestieDev#1574]
some tasks show the wrong language in tooltip and questie tracker
![11](https://user-images.githubusercontent.com/36725494/69274449-56e64700-0c15-11ea-8e91-bdfeab2c78ce.jpg)
![QQ截图20191121041331](https://user-images.githubusercontent.com/36725494/69274465-5d74be80-0c15-11ea-9ef5-30734b1e992f.jpg)
![QQ截图20191121041331](https://user-images.githubusercontent.com/36725494/69275056-9e210780-0c16-11ea-9ef8-e7d6ef3055e8.jpg)
![未标题-2](https://user-images.githubusercontent.com/36725494/69275181-dd4f5880-0c16-11ea-9f2d-fe1417650bde.jpg)
![未标题-3](https://user-images.githubusercontent.com/36725494/69276346-4506a300-0c19-11ea-8a60-353229a675bc.jpg)
![QQ截图20191121044127](https://user-images.githubusercontent.com/36725494/69276383-56e84600-0c19-11ea-9b3d-5070360b51b4.jpg)
![QQ截图20191121044154](https://user-images.githubusercontent.com/36725494/69276391-5b146380-0c19-11ea-89b4-ff138c40c38b.jpg)
Questie-v5.2.2

**Comment by drejjmit** [comment]
Hello. 

This is due to language data missing on Wowhead:
_https://cn.classic.wowhead.com/quest=1045/raenes-cleansing_
_https://cn.classic.wowhead.com/object=31/old-lion-statue_
_https://cn.classic.wowhead.com/quest=249/morganth_

You can help by uploading collected data with 
https://www.wowhead.com/client

**[1284] = {"Suspicious Hoofprints",{nil,{187273,}**
**[1268] = {"Suspicious Hoofprints",{nil,{187273,}**
Is actually given by object 21015 and not 187273 so this have to be changed in the DB. After that it will show the correct translation.

**Comment by BreakBB** [comment]
Hey @SqiChiu 

Thanks for this report! We're always trying to complete our database to show things correct for all the languages. As Drejjmit already wrote, we're still missing translations for some objects/quests/items and it would be very helpful if you would install die [Wowhead client](https://www.wowhead.com/client) so you'll help adding those translations to Wowhead.
We're grabbing our translations from there.

**Comment by drejjmit** [comment]
[21015] = {"Hoofprints",nil,nil,nil,0,},
[21016] = {"Hoofprints",nil,nil,nil,0,},
No spawn location. Doesn't show up on map.
Use same data as Suspicious Hoofprint
 [15]={{29.7,47.64},},},15,},

**Comment by BreakBB** [comment]
@SqiChiu Do you still experience issues?

**Comment by BreakBB** [comment]
This issue is being closed due to lack of information. It will remain archived in GitHub should more information become available.
