### ISSUE TITLE
Says out of date

### ISSUE THREAD

**Issue by rossbg91** [AeroScripts/QuestieDev#1618]
## description
Says that the version of Questie is out of date but it is the latest version on the site... says its was uploaded 8 hrs ago. 

## Questie version
v5.3.0

**Comment by BreakBB** [comment]
@rossbg91 As already answered for others on Discord: Since Blizzard updated their interface version, Questie has to reflect that new number in its files as well for it to be "up to date". We weren't aware of the change, but **there is no problem here**! Questie will run the same as before and with the next release we will change the number so it is listed correctly.

**Comment by rossbg91** [comment]
Got it! Thank you will read more about it on the discord which I just joined :)

**Comment by BreakBB** [comment]
Fixed with f3edde0f2c8f70ea69d136988975ec1fa49a255d
