### ISSUE TITLE
Stones of Binding quest error

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#1684]
## Description
The Cresting Key for the quest Stones of Binding is showing at the west binding circle. It should be at the east binding circle.

## Wowhead link
https://classic.wowhead.com/quest=651/stones-of-binding

## Screenshots
![Screenshot from 2020-01-04 14-34-41](https://user-images.githubusercontent.com/29320668/71770817-8208c980-2f29-11ea-8609-ef940b7cdba9.png)

## Questie version
v5.4.1

**Comment by BreakBB** [comment]
@woopydalan It is working fine for me as you can see below:

![image](https://user-images.githubusercontent.com/33514570/71779813-25092400-2fba-11ea-99f9-3c8d2865379f.png)

This might be because of missing translations. As I see in your screenshot the translation for the "Stone of West Binding" is missing.

**Comment by woopydalan** [comment]
It exists on wowhead in spanish 
https://es.classic.wowhead.com/object=2689/piedra-de-v%C3%ADnculo-occidental

**Comment by BreakBB** [comment]
@woopydalan Looks like the esES and esMX translations differ on this quest. The translations for the keys we have are:

```lua
[4483] = "Llave ardiente",
[4484] = "Llave emblemática",
[4485] = "Llave del trueno",
```

But in your screenshot it's `Llave blasonada`. So we aren't able to match it correctly. Am I mistaken?

**Comment by woopydalan** [comment]
@BreakBB that is correct, the esMX for the cresting key does not match esES
