### ISSUE TITLE
Questie's GPS-API exposed

### ISSUE THREAD

**Issue by rsheep** [AeroScripts/QuestieDev#17]
Would be really nice to have the ability to Add/Edit/Delete notes from other Addons.

For example, VanillaGuide could use Questie (and Cartographer) for its note/GPS-positions.

Back then when I started developing it (that was a LONG time ago), MetaMap+BWP seemed the best choice (it was the only way to have a "cheap" pointing arrow).
Now if you're going to implement Cartographer+Pointing_Arrow I see no reason to keep the "heavy" MetaMap around.

**Comment by Schaka** [comment]
We are currently writing Questie in such a manner, that it should be possible to do exactly that. Once the quest tracking system is far enough advanced to be merged into the master branch, I'll hit you up on IRC and we'll see if we can figure out how to best make the API available to other addons.

**Comment by Schaka** [comment]
Please have a look into https://github.com/AeroScripts/QuestieDev/commit/20daefe46e37cbd5374df1bc96ab7a0688e49733

In particular, SetCrazyArrow() is where it's at. We will expand upon that, after we did the move to Astrolabe and then hopefully expose our API so that you can easily add a waypoint to the arrow on any possible map.

**Comment by Schaka** [comment]
Call ArrowShown() first, then
SetCrazyArrow(point, dist, title)
Whereas point is a table containing 
```
{
c = continentId,
z = zoneId, -- also known as (mapId)
x = noteX,
y = noteY,
}
```
