### ISSUE TITLE
Armor types that I should not use are shown in white now

### ISSUE THREAD

**Issue by crinavar** [AeroScripts/QuestieDev#171]
After installing the addon, version 2..12, the armor types show in white, as if I could use them. I am rogue and I could see this for Mail type armor. There must be an issue with the color of the armor type being displayed white instead of being red or the corresponding one whenever it is appropriate.

Running on 1.12 Nostalrius begins PVP

**Comment by Dyaxler** [comment]
Hmmm... that is very interesting. I too ran into this issue last night but it didn't occur to me that it might be Questie. I'll see if I can try and repro this today.

**Comment by Dyaxler** [comment]
I tried to get this to repro today and couldn't. Perhaps maybe it was a fluke but I suspect not because I do remember thinking that it was weird that I was looking at a piece of leather armor and the tooltip suggested that I could wear it. Without a consistent repro... I wouldn't know where to look in the code for the bug.

**Comment by Dyaxler** [comment]
I haven't seen this issue pop up on my Priest, Pali or Warlock this past week. What ever is causing the bug might not be Questie related.
