### ISSUE TITLE
Missing quest markers: [Dig Rat Stew, Rig Wars, Chief Engineer Scooty, The Darkmoon Faire]

### ISSUE THREAD

**Issue by Walobyte** [AeroScripts/QuestieDev#1756]
## Description
Horde - Priest - Undead - lvl 27 
1. Dig Rat Stew (Barrens - 55.3, 31.8) not showing up as a quest marker. Does not appear to patrol. (Currently 'green' quest)
2. Rig Wars (Orgrimmar - 75.8, 25.1) not showing up as a quest marker. Does not appear to patrol. (Currently 'red' quest)
3. Chief Engineer Scooty (Orgrimmar - 75.8, 25.1) not showing up as quest marker. Does not appear to patrol. Requires 'Rig Wars' to be started. (Currently 'red' quest)
4. The Darkmoon Faire (Orgrimmar - 51.0, 72.3) not showing up as quest marker. Patrols around 'Valley of Strength' (Currently 'red' quest)

## Wowhead link
1. https://classic.wowhead.com/quest=862/dig-rat-stew
2. https://classic.wowhead.com/quest=2841/rig-wars
3. https://classic.wowhead.com/quest=2842/chief-engineer-scooty
4. https://classic.wowhead.com/quest=7905/the-darkmoon-faire

## Screenshots
![image](https://user-images.githubusercontent.com/60037622/74088944-caa42d00-4a69-11ea-8f10-d2f09d96ae3d.png)
![image](https://user-images.githubusercontent.com/60037622/74089027-c0366300-4a6a-11ea-829a-4e0fb321122e.png)
![image](https://user-images.githubusercontent.com/60037622/74089106-afd2b800-4a6b-11ea-9e9d-1d4df3dcd815.png)

## Questie version
v5.6.0

**Comment by BreakBB** [comment]
@Walobyte Thanks for this detailed report :+1: I will check them tomorrow to find out what could be wrong with them and most likely need some more information from you.

**Comment by Walobyte** [comment]
Update: 

I leveled up to 28 and the quest 'Rig Wars' is now showing up through Questie map/minimap. Basically you can pick the quest up at 26 or 27, but Questie does not show it until 28+. (This extends to quest 'Chief Engineer Scooty')

This may be the same case for Darkmoon Faire, as when I pick up the quest, its labeled as 60, however I believe you can pick this up at level 1.

As for Dig Rat Stew, the only assumption I can gather - this is a cooking specific quest. The reward gives a 90+ Cooking recipe, and I am only level 23 cooking. Not sure if Questie factors in the profession level vs current level when picking up profession quests.

**Comment by BreakBB** [comment]
@Walobyte

1. "Dig Rat Stew" is listed as a level 23 quest which can be picked up starting at level 15.
For the required profession skill this is a real edge case, because you need to be "Journeyman" without a specific skilllevel )so basically you can pick it up with cooking level 50).

We don't include the required cooking rank, but just the skilllevel. So what we do as a (dirty) workaround is to check if the skillevel is at least 76 which automatically means the player learned Journeyman cooking.

2. Yes this is a known issue, because we're (at this point) checking for the suggested level of a quest instead of the required level. Since this quest is listed as a level 35 quest, Questie doesn't show it until level 28 by default. You can pick it up starting at level 25. We are planning to (finally) change this in near future, but it requires some testing and quite some changes.

3. Strange that the quest doesn't show up 🤔 We are checking if a quest is a child-quest (like this one) and don't care about any other requirement. Meaning child quests should always show up if you pickup the parent quest.

4. Working on the Darkmoon Faire quests already. Don't really have reliable data for them yet, but will have once the faire started.

**Comment by Walobyte** [comment]
@BreakBB  Thanks for the quick responses. All sounds acceptable to me. I will close this bug as 
- Item # 1 does in fact work, just requires higher level cooking
 - Team has a backlog item to retrofit item # 2  
 - Team is are already looking into item # 4 

Thanks

**Comment by BreakBB** [comment]
@Walobyte Thanks again for this very detailed report. We're looking forward to more reports from you ;)
