### ISSUE TITLE
Quest sort by Xpac

### ISSUE THREAD

**Issue by Rilos88** [AeroScripts/QuestieDev#1774]
## Description

I use Questie in WoW Classic and would like to use it in BfA (and future xpacs), but I am also working on some old xpac quests in Legion.  I would like a way to sort the quests into groups so I can collapse or otherwise close the xpac quests I am not working on to clean up the view in Questie for the areas in am working in currently.  I am referring to how the quests look in the main window while out and about int he world and not in the quest log that shows what you have and have not completed.

**Comment by BreakBB** [comment]
What exactly would you need Questie for in BfA or Legion? :thinking:

Supporting other xpacs isn't really easy because of the way out database works. All the quests in their represent the state in Classic. For other xpacs you would have to reflect changes to such quests, remove outdated and add all the new quests.

This is no easy task. I honestly think that the best way would be to add more `QuestieQuestCorrections.lua` and other correction files to reflect the differences and load such corrections respectively for the xpacs.
