### ISSUE TITLE
Questie making me crash

### ISSUE THREAD

**Issue by aminoo10** [AeroScripts/QuestieDev#1783]
Just reinstalled wow classic and have reinstalled my addons multiple times. Went ahead by disabling all of the other addons and it seems that questie is the culprit. Also tried deleting my Cache folder and much more, and I dont see how to resolve this. 

Basically what happens is while questie is enabled, if it at all tries to load, I first get disconnected from my account back to the login page. After trying to log back in, the game will crash and give me a Error 123 message (ive gotten both error 123 and 132). 

No idea what it is that I may have that is doing this, never had this problem in the past, just now as I've tried to play the game recently, if you guys could offer some troubleshooting tips or ideas it would be really appreciated, I really wouldn't want to use another quest addon, you guys really have one of the best ones out there. 

Thanks again

**Comment by BreakBB** [comment]
@aminoo10 Did you try older versions of Questie?
As already explained on Discord there is not much we can do as Addon developer since such crashes are caused by the WoW client handling something wrong.

Could you add a screenshot of the error to the issue? And you can reproduce this crash if you have just the latest Questie version active?

**Comment by BreakBB** [comment]
This issue is being closed due to lack of information. It will remain archived in GitHub should more information become available.
