### ISSUE TITLE
Search by level?

### ISSUE THREAD

**Issue by Klala** [AeroScripts/QuestieDev#1847]
Hello, I have noticed you don't have a search quest by level which is something I would like to see.
Would it be possible to add?

**Comment by BreakBB** [comment]
@Klala Hey, sorry for not coming to this earlier. I am not sure how you want this to be implemented. Since Classic includes over 4000 quests I don't think showing all quests for level X will be very useful.

If you want to find quests for a specific level(range) you can use the "Enable absolute level range" option in the general settings. These are not working really correct in v5.10.3, but will work perfectly in the upcoming release v6.0.0.

**Comment by Gogo1951** [comment]
Maybe we can revisit this in the future, but there are higher priority things we need to look at first.
