### ISSUE TITLE
"[52] Torwa Pathfinder" in Feralas (Jannos Lighthoof) shows as available to Alliance player 

### ISSUE THREAD

**Issue by Gh4stly1** [AeroScripts/QuestieDev#1849]
At Camp Mojache.  I was not able to get close enough to determine whether it was also displaying a ? over the NPC before I was guardspanked.

https://classic.wowhead.com/npc=8142/jannos-lighthoof

My character is a Night-elf Druid, which may play a role in the erroneous offering of the quest, as the NPC is a (Horde) Druid trainer.

**Comment by BreakBB** [comment]
@Gh4stly1 Sorry for the late response. I just had a look and the latest version of Questie actually has some issues with some quests which have the same ID for both factions. So quest NPCs are showing to both factions. But this has already been fixed with 2c95cabda2b8e650370097834769677e262ec93c and will be released with the upcoming Phase 4.
