### ISSUE TITLE
Quest log volume in tracker

### ISSUE THREAD

**Issue by MarkusNemesis** [AeroScripts/QuestieDev#187]
I'd like to suggest that the tracker window by default show the number of quests in the quest log.
Many times I've gone to get a quest without noticing I've no room in my log.

This will hopefully also fix the issues I've been having with the tracker window being empty and my inability to click around the screen. It seems like when empty, the tracker takes up an invisible part of the screen and stops me from moving the camera etc. 

Cheers,

**Comment by Dyaxler** [comment]
I'll look into adding a user toggle to turn on "number of quests in quest log". Not everyone will want to use that and most users like to keep things clean and simple looking. Should be easy enough to add it as a toggle though.

I reduced the default size of the container... it auto sizes vertically when quests are added. I'll make it auto size horizontally too. That way I can reduce the container size to 1x1 pixels. That should be small enough to not interfere with your clicking.

I've also been thinking about making it populate quests UP instead of DOWN. I have my Tracker toward the bottom of my screen and I'm having to move it up when I have more than X number of quests being tracked.

**Comment by MarkusNemesis** [comment]
I personally have my tracker on the top of the screen, so you will need to
make this a player changeable option.

**Comment by Schaka** [comment]
Just implement a timer that does the same thing the toggle questie button does (twice!) every 2 seconds and you're good. The 2.0 branch is full of hackfixes anyway.

**Comment by Dyaxler** [comment]
I didn't quite do it that way but I did add the toggle function twice in tons of places.

The issue that Markus is describing above is that when the QuestTracker is empty the main frame is hidden and is taking up 200 x 200 Pixels. I wrote some additional code to auto resize the frame from 1x1 to how ever big it needs to be. That way when the tracker is empty it's size is minuscule and the likelihood of anyone accidentally landing on a 1x1 pixel is slim.

**Comment by Dyaxler** [comment]
New version v2.62 available...

There is a new option to turn on a Header in the QuestTracker which will display the number of active quests in your log (#) / out of max number (20). It's disabled by default so you'll have to use the command line to turn it on. Use /questie trackerheader to toggle it.

The QuestTracker now auto sizes itself. If there is nothing tracked it shrinks to 1x1 pixels. I can't shrink it to 0x0 or it's screen position will be lost and it will error out if you re-track quests or try to move the QuestTracker. In the interest of time, I decided to not figure out how to code around that. It's just easier to make it 1x1. Besides, it's impact will be almost nil since it's so small. The odds of you hitting it while moving your camera around is minuscule.

You can also change the direction in which the QuestTracker grows. Upwards or Downwards using /questie trackerlist 

/cheers

**Comment by Dyaxler** [comment]
Is new header enhancement working for you?

**Comment by MarkusNemesis** [comment]
Heya, I've just moved house, so I've not been in a good position to test.
I'll get back to you ASAP.

**Comment by Dyaxler** [comment]
Resolved?
