### ISSUE TITLE
Quest ! marks not disappearing after accepting a quest.

### ISSUE THREAD

**Issue by MarkusNemesis** [AeroScripts/QuestieDev#190]
In certain circumstances, the ! mark on the minimap is not disappearing after accepting a quest, and will not resolve itself via the toggling of /questie mapaids

This is on a new character, questing in Redridge (where quests are also showing as ! on the minimap but are not available...)

**Comment by Dyaxler** [comment]
I've tweaked a number of functions in Questie so I can't say for certain if your issue will be resolved. Please upgrade to v2.62 and test again. Also, when you do upgrade, please use the new command line feature - /questie clearconfig. It won't clear your quest database but will update your profile settings. Log out then log back in and retest.

**Comment by Dyaxler** [comment]
Were you able to retest this?

**Comment by AriinPHD** [comment]
Pitching in. I was having the same issue as MarkusNemesis was having. I performed this /questie clearconfig command and relogged as suggested by Dyaxler. This seems to have completely resolved the issue for me.

I **am** seeing the issue with quests that Questie doesn't understand I've already completed. (E.g. I completed it but Questie hasn't registered this). A relog after completing such quests removes the "!" from the maps. I have only seen this once - right after upgrading - so it might be an issue from older versions.

**Comment by Dyaxler** [comment]
If you're running EQL3 it might be related to what you're seeing. I found a new bug last night that is playing havoc with Quest Completion. I discovered it while working on improving the Manual Quest Complete feature and marking ALL quest hashes as complete rather than just the first one... I need to resolve the EQL3 bug first before I can finish the rest.

**Comment by Dyaxler** [comment]
I've got this fixed in my local version. Still doing regression testing. No ETA yet but I've confirmed that Questie works fine without EQL3...

**Comment by Dyaxler** [comment]
I've fixed all the issues with EQL3 and Questie. Please try 2.65.

**Comment by mailbox112** [comment]
yea having the same problem when I was first installing this I read that you had to move the WoW base folder out of programfiles x86 and create a WTF folder I can find that info anymore did I need to move the WoW folder because now when I launch blizzard it says the game isn't in its intended location I can still play WoW was just wonder if you could repost the info here or something to help me out
