### ISSUE TITLE
Into The Scarlet Monastery

### ISSUE THREAD

**Issue by blixten85** [AeroScripts/QuestieDev#1908]
The quest Into The Scarlet Monastery does not show up in Undercity when you reach level 33. I had to run to Varimathras manually to pick it up. I wasn't sure if i had to do anything special in order to unlock this thanks to questie not showing this quest on the map.

The quest in order.
https://classic.wowhead.com/quest=1048/into-the-scarlet-monastery#guides

EDIT: Yes im running the latest version of questie downloaded from twitch application.

Best Regards

**Comment by Gogo1951** [comment]
I just did this quest, didn't see an issue with it. Can you screenshot what you're seeing? I literally ran this Monday night on my 37 Orc Warrior -- and I got the quest because I'm pretty sure it was on the map for me to get. I had paid someone to run me, so it wasn't that anyone shared it. Hmm, just please double check?

Also what race are you? There is one quest in there that doesn't work for Undead... maybe something to look into if that flag is set for this quest as well. Thanks!

**Comment by Gogo1951** [comment]
Hey, I think setting is the issue for why you don't see it at 33. (= Quest is much higher than 33, but if you max the level cap you'll see the harder quests.

![image](https://user-images.githubusercontent.com/55365231/80554827-f7dee800-8993-11ea-97d4-c7112ae6586a.png)

**Comment by Gogo1951** [comment]
Hey @Muehe I think the default should be to show all quests a person can get, meaning set the dial to "show up to 60" and let let them show up as they are available to the user. What we have now is a bit weird, like @blixten85 pointed out. There are quests you can get, but we don't show them since they are too high level. Let's just let WoW availability dictate what gets shown.

**Comment by blixten85** [comment]
> I just did this quest, didn't see an issue with it. Can you screenshot what you're seeing? I literally ran this Monday night on my 37 Orc Warrior -- and I got the quest because I'm pretty sure it was on the map for me to get. I had paid someone to run me, so it wasn't that anyone shared it. Hmm, just please double check?
> 
> Also what race are you? There is one quest in there that doesn't work for Undead... maybe something to look into if that flag is set for this quest as well. Thanks!

Hey!

Ok, i was on my level 33 Undead Rogue. Maybe that's why then. 
Default settings of Questie, and latest twitch version.

**Comment by BreakBB** [comment]
Merging this with #1568 

I am planning to make this happen for the next update.
