### ISSUE TITLE
Need Consistent UX for "Use At Location" Items

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1937]
## Description

There are a few quests that call for you to use an item at a location... not on an item, not on an NPC... and so there's nothing showing on the map around what you have to do. It'd be good if we had a little gear icon, or something along those lines, indicating that you had to take some action.

Here's a few examples.

https://classic.wowhead.com/item=4823/water-of-the-seers for https://classic.wowhead.com/quest=772/rite-of-vision

* NOTE: Needs some sort of Gear Icon on the map.

https://classic.wowhead.com/item=10338/fresh-zhevra-carcass for https://classic.wowhead.com/quest=882/ishamuhale

* NOTE: Needs some sort of Gear Icon on the map showing where to drop the Fresh Zhevra Carcass to summon Ishamuhale. I don't believe that Ishamuhale showed up on the map at all. I have to re-do the quests in that zone to re-test. Also the Zhevra's created so much clutter, suggest we not show the carcass as an objective as it makes it impossible to do other quests while that's on there.

https://classic.wowhead.com/item=5165/sunscale-feather for https://classic.wowhead.com/quest=905/the-angry-scytheclaws

* NOTE:  The Raptors created so much clutter, suggest we not show the feather as an objective as it makes it impossible to do other quests while that's on there. Just show the nest locations.

https://classic.wowhead.com/item=5810/fresh-carcass for https://classic.wowhead.com/quest=1136/frostmaw

* NOTE:  The cats created so much clutter, suggest we not show the carcass as an objective as it makes it impossible to do other quests while that's on there. Just show the flame locations.

https://classic.wowhead.com/item=9530/horn-of-hatetalon for https://classic.wowhead.com/quest=3062/dark-heart

* NOTE: Needs a gear icon indicating where to use the horn to summon the quest mob. Also suggest we not show all the harpies that drop the horn as it creates too much clutter.

**Comment by Gogo1951** [comment]
Find the guy's dead wife, and murder her? Ha. We need more consistent "use / talk" icons. Not all quest can be solved with a sword. But at least the location is right! (=

![WoWScrnShot_052320_175613](https://user-images.githubusercontent.com/55365231/82756385-93028c00-9d9f-11ea-9623-d6216dcb3a0e.jpg)

**Comment by BreakBB** [comment]
@Gogo1951 This consistency currently heavily relies on the way Blizzard tracks a quest and it's objectives.

Whenever the API gives us an objectives with <NPC 0/X> we add a sword icon. And for Mankrik's Wife it is the same as with a few other quests. You don't have to kill something, but interact with it. But Blizzard just gives us the <NPC 0/X> stuff. The same goes for quests were a gear icon would make much more sense but since it is not the correct objective type, we add a different icon.

If we want to differentiate such things that would most likely require a lot of work on the DB to add overwrite values to the quest type of such quests. It is possible though.
