### ISSUE TITLE
!Questie\QuestieTracker.lua:835: attempt to index global 'QuestieTrackerHeader'

### ISSUE THREAD

**Issue by Pr1mu5** [AeroScripts/QuestieDev#195]
Right after i turned in "Clamlette Surprise" in Tanaris i got literally spammed by this error message:

[2016/03/24 00:15:59-609]: !Questie\QuestieTracker.lua:835: attempt to index global 'QuestieTrackerHeader' (a nil value)
!Questie\QuestieTracker.lua:835: in function `removeQuestFromTracker'
!Questie\QuestieQuest.lua:68: in function `CheckQuestLog'
!Questie\QuestieAstro.lua:186: in function `OnUpdate'
<string>:"Questie:OnUpdate":2: in main chunk

(newest release 2.62 + EQL3)

SS:http://i.imgur.com/0lNnen1.jpg

**Comment by Dyaxler** [comment]
You need to run /questie clearconfig in game. The code is looking for the new Header feature and it's error'ing because the entry doesn't exist in your SavedVariables file yet.

You just reminded me that I really should have added better "Error Checking" for the new entries. I've committed a fix but you'll have to download the file separately as it's not packaged with the 2.63 release. Or run the command above.

https://github.com/AeroScripts/QuestieDev/commit/99d9b7d4d3506383ef7d39517cfd0d7b97abb61c

**Comment by Dyaxler** [comment]
Never mind... if you haven't already done it. I've updated the release with a new zip which contains a couple of hot fixes.
