### ISSUE TITLE
Quest issue around [14] The Demon Seed

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#1962]
## Description

The quest calls for you to pick up a stone next to the quest giver, but there's no gear icon on the Questie map indicating that you need to pick up the stone. The object is right next to the quest giver. Tested on a level 11 Troll Hunter.

## Wowhead link

* The Demon Seed - Quest - World of Warcraft || https://classic.wowhead.com/quest=924/the-demon-seed

* The Demon Seed - Object - World of Warcraft || https://classic.wowhead.com/object=3524/the-demon-seed

## Questie version

5.10.3

**Comment by BreakBB** [comment]
@Gogo1951 When you pick up this quest the quest [Flawed Power Stone](https://classic.wowhead.com/quest=926/flawed-power-stone) should show up which is a child quest of The Demon Seed. Didn't it?

At this point we can't just add "gear icons" for quests, because those are reserved for real objectives.

**Comment by BreakBB** [comment]
@Gogo1951 Any news on this?

**Comment by Digital-Tectonics** [comment]
You need the item on next to the quest giver and you have to interact with the location at the mountain (which is not a gear but shows one on mouse over).
