### ISSUE TITLE
Quest list tracker thing

### ISSUE THREAD

**Issue by Borkatjov** [AeroScripts/QuestieDev#197]
Seems like I can't move the quest tracker which used to be on the side below the minimap. It's stuck in the left corner, right over the player portrait

**Comment by Borkatjov** [comment]
http://i.imgur.com/ZZwDE4p.jpg

**Comment by Dyaxler** [comment]
Go into your quest log and enable more quests to make the list longer... then use SHIFT+CTRL+Click and drag it to your desired position.

Or do a /questie clearconfig and it'll reset the tracker and place it on the left side of your screen in the middle allowing you to get to it. However, clearconfig will reset your preferences. If you're playing with all the defaults then you should be ok otherwise you'll have to reflag your preferences. I.E. turn boldcolors back on or turn the header back on etc.

**Comment by Borkatjov** [comment]
Hey man, that first trick fixed it! It's just weird without the small black transparent box that used to be there, it was easier to move around like that.
 Regardless, thanks for the help, this addon is fucking GOD.

**Comment by Dyaxler** [comment]
Yeah... the black background, which at one point had code that auto sized it, was causing serious lag. If I defined a static width the background would remain even if hidden (no quests tracked) which was causing issues interacting with the objects in the Worldframe. So... I had to remove the background.

**Comment by Borkatjov** [comment]
Ah, that sucks. Thanks anyway pal, I really apprecaite it

**Comment by Dyaxler** [comment]
You're very welcome
