### ISSUE TITLE
Questie Log on Error

### ISSUE THREAD

**Issue by psycholollypop** [AeroScripts/QuestieDev#2032]
Hiya,

So I've enabled Questie in the addons menu and ticked load out of date addons, it's in the addons folder and all requirements are checked. However every time I log on I get the error message seen in the attached picture. I've relentlesly searched the internet for a fix but can't find anything. After I close the error message, nothing shows on my screen or the map screen to do with questie. 
Not sure how to fix this? 

<img width="512" alt="Questie Error" src="https://user-images.githubusercontent.com/66946802/84645290-3d318780-aef8-11ea-9904-aaf058cdfb21.png">

**Comment by BreakBB** [comment]
Check [the FAQ point 21](https://github.com/AeroScripts/QuestieDev/wiki/FAQ#21-i-get-an-error-on-startup-about-callbackhandler-10lua90-unexpected-symbol-near-).

You're trying to run an updated version of Questie on a private server. Since a lot of updates Questie is **for Classic only** and not supporting private servers anymore. However you can grab [v3.7.1](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.1) which is the last Questie version for 1.12.
