### ISSUE TITLE
A Light in Dark Places

### ISSUE THREAD

**Issue by Cerby3BR** [AeroScripts/QuestieDev#2046]
The Midsummer Festival quest A Light in Dark Places doesn't disappear from the minimap or map, even after having picked it up. Possibility : there are two such quests in the database, one marked for Horde and one for Alliance, but both are marked as being started by the same NPC, the Festival Flamekeeper, and one follows the other. There's a possibility that the second one is repeatable.

https://classic.wowhead.com/quest=9319/a-light-in-dark-places
https://classic.wowhead.com/quest=9386/a-light-in-dark-places

![WoWScrnShot_062120_044948](https://user-images.githubusercontent.com/54936174/85215624-bd823d80-b37b-11ea-986d-995640ee0dbb.jpg)
![WoWScrnShot_062120_044954](https://user-images.githubusercontent.com/54936174/85215625-bfe49780-b37b-11ea-81b6-898b78ccdb84.jpg)

Version 5.10.3

**Comment by drejjmit** [comment]
Does it show after a ``/reload``?

**Comment by Djfe** [comment]
The other thing is: you can see the horde questgivers as alliance.

**Comment by Cerby3BR** [comment]
It still shows after logging out and back in. And as you can see, both factions see all six questgivers.

**Comment by Cerby3BR** [comment]
Edit with more details.

**Comment by drejjmit** [comment]
These festival npcs have the same npc ID for Horde and Alliance so that means you can pick them up as horde in Ironforge or as alliance in Orgrimmar. I wouldn't recommend it but it's actually correct to show those pickup locations.

As for A Light in Dark Places it's correct for Alliance. I can only see one quest.
Can't test Horde since i don't have a 50+.
Maybe @BreakBB can test this.

**Comment by Cerby3BR** [comment]
I can confirm that 9319 is the first quest, and 9386 is the repeatable follow-up quest. Neither should be faction-specific.

**Comment by drejjmit** [comment]
Which of them show as available? Go to Questie Settings > Advanced and check "Show Quest IDs". Also check the id of the one you picked up (Should show the quest ID on the tracker)

**Comment by Nerillida** [comment]
The quests A Light in Dark Places are for both factions.
https://classic.wowhead.com/quest=9319/a-light-in-dark-places is first
https://classic.wowhead.com/quest=9386/a-light-in-dark-places is second. Unsure if it's repeatable but typically is with otherwise identical quests.

NPCs
Festival Talespinner Horde Only
Festival Loremaster Alliance only
Festival Flamekeeper - both factions
