### ISSUE TITLE
User disabled quest in Quests by zone

### ISSUE THREAD

**Issue by northmage** [AeroScripts/QuestieDev#2090]
## Description

Some quests likes Desolace centaur clans quests are selected by the user.

If so, the opposite quest is still active, but most users do not play it. 

But that quest is still in the list of Available Quests in Quests by zone.

It is very annoying and confusing.

Therefore, it would be nice to make a list of quests disabled by the user under the list of completed quests, and allow unwanted quests to be put there.

**Comment by BreakBB** [comment]
@northmage Just to make sure I understand you correctly: You want another category in the Journey where you can place specific quests which you want to ignore? Or is it just to hide them from the map?

**Comment by northmage** [comment]
@BreakBB "You want another category in the Journey where you can place specific quests which you want to ignore?" < correct.

I don't want to see the quest which is virtually impossible in 'available quests' category.

**Comment by BreakBB** [comment]
@northmage With "virtually impossible quests" you mean quests you can't pick up "right now"?

**Comment by northmage** [comment]
@BreakBB No. Like the example of first article, it means that can accept, but extremely difficult or must choose one.

Like Desolace centaur clans quests. If you first stand for Magram, you can accept Gelkis quest, but it is very hard to clear it. So most of players do not do both of them. So one quest line is remained. But it is very difficult.

If someone want to stand for opposite centaur clan after he/she finished certain centaur clan quests, he/she must slay at least 325 centaurs of the clan he/she first stand for. Who want to do that?

**Comment by BreakBB** [comment]
@northmage Well the target of Questie is to show all quests which are available for a player. The example you stated is clearly an example where it requires a lot of effort to fulfill a quest, but since it can be done, we want to show it.

Players can always hide quests if they don't like them or simply want to remove them from the map.

The Journey is a totally different place as that should really be a place where a player can reliable see what quests are open for them to do. We have people in the community who want to finish every single quest they can do in the game. It would be misleading to hide quests just because they are "not really worth doing".

**Comment by Gogo1951** [comment]
You can hide quests by Shift + Clicking on the quest. No way for us to programmatically predict which quest a user would want to take, or re-visit.
