### ISSUE TITLE
Port to TBC?

### ISSUE THREAD

**Issue by CoolFangs** [AeroScripts/QuestieDev#213]
I realize this is a long shot, but figured it can't hurt to ask.

Basically I think it would be cool to see this addon ported to TBC 2.4.3. I don't know enough about making addons to know how hard this would be. I much prefer this addon to QuestHelper, the most popular questing addon used in TBC.

**Comment by Dyaxler** [comment]
I've already branched a TBC version that made a snapshot of the zone data before Muehe's Vanilla fix. I agree with you that there needs to be a TBC version. However, most people use QuestHelper and personally I think it sucks. It doesn't show WHERE to get the quests. There are other mods I've tried such as Cartographer_Quests and it works "OK" but it's not as intelligent as Questie is in Vanilla. I'm in the process of getting setup to see if Questie plays nice in the TBC. 

Might need to update some functions AND I'll need to figure out a way to update the database with TBC quest data since no Outlands quests exist in the current database. There is a some kind of a parsing program written in Java that refactors the questhelper database but I have no idea how to use it.

Contrary to what most people think of me and my ability to keep this project going, I'm not a developer and don't possess the skills to rebuild the database. I could figure it out as there is plenty of info to read up on but I've never done it. I could install Visual Studio and play around with the Java script to see if I can figure out how it works.

**Comment by Dragoma** [comment]
have been trying to find a good Quest help on TBC

**Comment by Dyaxler** [comment]
Funny that you should ask... I finished the QuestieTBC client today. I'm waiting for an updated database to be created by one of the original authors.

**Comment by CoolFangs** [comment]
Look forward to seeing it!

**Comment by Dyaxler** [comment]
It's up in the QuestieTBC branch... you can select the branch click the Download Zip icon. Then just copy the !Questie directory over to your Addon folder. You don't need any of the other files outside the !Questie directory.

**Comment by Dragoma** [comment]
thx for that does the outland Q also work?

**Comment by Dyaxler** [comment]
I mentioned in the release notes that no, not yet. I'm waiting for a tool to be updated that might give me the ability to create an updated database that will include all the Outland quests.

**Comment by Dragoma** [comment]
kk thx for ur work

2016-04-25 6:09 GMT+02:00 Dyaxler <notifications@github.com>:

**Comment by ooxamon** [comment]
asd

**Comment by ooxamon** [comment]
Did you ever update for TBC quests?

**Comment by Muehe** [comment]
Not yet, although we might do so sometime™ in the future. The branch is there for archiving purposes.

**Comment by ooxamon** [comment]
Ah okay. Thank you for replying. Was hoping there would be some resource
available for TBC other than quest helper.

**Comment by Muehe** [comment]
There is an addon called Carbonite, which is a full map addon including a quest helper I think.
