### ISSUE TITLE
Couple of small QoL changes to tracker

### ISSUE THREAD

**Issue by zylya** [AeroScripts/QuestieDev#2155]
## Description

A couple of extra options for the tracker would be great:
1) option to wrap text OR reduce the indentation of quests - for longer objectives (or if the frame width is relatively narrow), the text can be cut off before it gets to the tracking portion - making it difficult to track quests
![questie_text_wrap](https://user-images.githubusercontent.com/5124797/86913139-1a207f00-c116-11ea-9902-c7681dda12e6.png)

2) option to disable fade completely. When my mouse enters the tracker, all of the quests fade out slightly, and then the specific quest that the mouse is over comes back to full alpha. I find the change a little jarring and would prefer to disable to fade-in/out change of alpha on the tracker. I've got the options "Fade Min/Max BTNs" "Fade Quest Item BTNs" and "Fade Background" disabled but there's no option to disable the fade of quest text. It is particularly annoying when I move my mouse from off the tracker and on to a quest - the quest that I hover over doesn't change but all the others do, as well as being distracting if my mouse unintentionally enters the quest tracker while doing something else.

Thanks for your work on the addon though - everything else about it has been amazing!

**Comment by zylya** [comment]
Found one more:

3. Option to hide completed objectives. As an example, on the quest Dangerous! (Horde - Hillsbrad) it shows:
Clerk Horrace Whitesteed: 0/1
Citizen Wilkes: 1/1
Miner Hackett: 0/1
Farmer Kabala: 1/1

It would be useful to have the two completed objectives hidden and just the outstanding ones still visible.

**Comment by Dyaxler** [comment]
#1 not going to do it... the tracker is already bloated enough with resize logic and automatically adjusting width based on font. We have to leave enough room to allow the Quest Item Buttons to be embedded. What I'm going to change is where the "truncation" breakpoint is so it doesn't cut off the Quest Progress numbers but rather just the Quest title.

#2 this is already on my to do list. We're going to update the Options panel and reorganize it so it will allow more options. Waiting for that to happen first before I add anymore options to the tracker tab.

#3 is also on my to do list along side updating the "Quest Complete" tags which are temporary "place holders". Eventually it'll tell you who to turn the quest into instead of a sudo Quest Objective saying "Quest Complete".

I'm not going to discount your suggestion in #1 entirely... I've already been thinking about a better way to indent things. And off the top of my head, I have an idea that shouldn't add anymore complexity/overhead. I'm also going to be adding the ability to shrink and expand the tracker frame vertically and add a scroll bar.

**Comment by zylya** [comment]
Lovely - that all sounds great. With respect to point 1, having the counter visible with the text truncated would work, the main problem is just not being able to see the objectives although the colour scheme (I use white-to-green) helps mitigate this a little.

**Comment by Gogo1951** [comment]
May be partially addressed in #2501 ; closing as a stand-alone issue.
