### ISSUE TITLE
Quest issue with Little Pamela

### ISSUE THREAD

**Issue by Gogo1951** [AeroScripts/QuestieDev#2204]
## Bug description

Quest shows on map, but is not available for pick up. Tested on 55 Tauren Druid.

* Little Pamela - Quest - World of Warcraft || https://classic.wowhead.com/quest=5142/little-pamela

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/88472377-c2389500-ced7-11ea-97fb-70b79d31c1a8.png)

## Questie version

6.0.2

**Comment by drejjmit** [comment]
You can either have 'Little Pamela' or 'Sister Pamela'. Not both. 
We currently don't hide 'exclusive to' when you pick up a quest,
In this case since 'Little Pamela' is 'exclusive to' 'Sister Pamela', this should be hidden when you pick up the other. 
Maybe a 6.1 milestone.
Important that such change doesn't hide 'exclusive to' if it's a 'parent quest'

**Comment by drejjmit** [comment]
This should also be fixed with https://github.com/AeroScripts/QuestieDev/commit/ee93b7dca09de68c8549056caf607aaebb2f1953
