### ISSUE TITLE
Questie Tracker not tracking quests

### ISSUE THREAD

**Issue by x003** [AeroScripts/QuestieDev#221]
Works fine in 2.67 but can not get it to add anything to the tracker in 3.0 for me

edit: I figured out it was the ShaguQuest EQL3 addon from http://shaguaddons.ericmauser.de/shaguquest/ causing the tracker to behave this way, although the two addons seemed to work fine together in the previous version.

**Comment by Dyaxler** [comment]
Hmmmm... interesting. I honestly don't see why they would conflict with each other.

You're going from a version that didn't have a version check so a /questie clearconfig wouldn't have been thrown. Can you do one and report back? No tracking data usually means that it's not being added correctly to the savedvariables file. It might be missing some DB keys.

**Comment by x003** [comment]
the clearconfig made no difference for me same issue still occurs if I use the ShaguQuest addon instead of the regular EQL3

**Comment by Dyaxler** [comment]
Just to be clear... you're playing on an English server?

**Comment by Dyaxler** [comment]
OK, so looking over ShaguQuest... he modified EQL3 and just called it ShaguQuest and added some custom code. It's not a "stand-alone" version of EQL3 so that's why it's not working with Questies tracker. The function calls aren't the same.

I generally don't do this but adding support for a specific addon is not something we generally do unless there is some kind of dependency on it. Since it's an easy fix I've just uploaded a hot fix for it.

Zip file updated with new hot fix:
https://github.com/AeroScripts/QuestieDev/releases/latest

**Comment by x003** [comment]
Works all good now :)
