### ISSUE TITLE
Item price grayed out when in a vendor screen.

### ISSUE THREAD

**Issue by Jamesv1** [AeroScripts/QuestieDev#225]
Using Questie v3.0, whenever I enter a vendor screen, the price of an item is grayed out.

After searching around, I found a similar post from a few months ago:
https://github.com/AeroScripts/QuestieDev/issues/146

This seems to be the exact same issue, and no fix is to be found.

**Comment by Dyaxler** [comment]
The only fix that I know of is to reload your UI. I honestly don't think Questie is the root cause as I've seen this behavior without Questie. I think it might be a tooltip "hiccup"... functions firing out of order or lagged to the point that they fire in the wrong order. I've tried to track down the exact function that triggers this but am unable since the issue happens, at least in my experience, random.
