### ISSUE TITLE
Questie stutter issue 

### ISSUE THREAD

**Issue by cronoss217** [AeroScripts/QuestieDev#226]
When hovering my mouse over a potential quest giver or vendor, my game stutters. I've narrowed down the addon that was causing the problem and found it to be Questie. Is there some sort of fix for this? I have noticed that this problem only occurs on my main character.

**Comment by Dyaxler** [comment]
It's not Questie. This tooltip bug has been in the Vanilla client for a very long time and happens when no mods are installed. Although, the more mods you have that insert data in the games tooltip, the more you notice it. There are tons of old blizzard forum threads complaining of this issue as far back and I can remember.

**Comment by cronoss217** [comment]
I see. Is there a way to solve the issue? I'm at wits end on what to do.

**Comment by Dyaxler** [comment]
From what I've read only nVidia cards suffer less from this issue. I've tried modifying my video settings to see if that had any effect. All I know is that it's a UI bug of some kind. If I knew which block of Blizzard code that was causing it, we could block it and code around it but I suspect it's UI code that isn't exposed.
