### ISSUE TITLE
Hide event/holiday quests when they aren't relevant

### ISSUE THREAD

**Issue by CoolFangs** [AeroScripts/QuestieDev#232]
Many quests specific to certain holidays show up on the map even if the holiday is not currently active. Would prefer these to be hidden unless the holiday is going on.

**Comment by Dyaxler** [comment]
Yeah. Me too. There aren't any markers or keys in the database that allows for that kind of filtering... yet. I'm hoping with a new database I will have that capability. We're working on something that might do the trick but I can't make any promises because the person working on the tool is very busy...
