### ISSUE TITLE
Samophlange Manual error

### ISSUE THREAD

**Issue by catpokemon** [AeroScripts/QuestieDev#2326]
## Description
 For the quest "Samophlange Manual" in the barrens, the drop item "Samophlange Manual Cover" is incorrectly shown to be from Venture Co. Defenders around the cave, while it is only available from killing Boss Copperplug.

## Wowhead link
https://classic.wowhead.com/item=11147/samophlange-manual-cover#comments

## Questie version
6.0.5

**Comment by drejjmit** [comment]
Hello.

Thanks for the report.
This is exactly how we have it already.
You should start using "Hold Shift" to check what the icons mean.

Drops from **Boss Copperplug** 
[11147]={"Samophlange Manual Cover",{3924},{**9336**},{}},

Drops from **Venture Co. Enforcer** / **Venture Co. Overseer** 
[11148]={"Samophlange Manual Page",{3924},{**3283,3286**},{}},

Since there is no quest progress until you combine the pages we can't stop showing the icons until the quest is done.
