### ISSUE TITLE
Implement full item database with loot table info

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#2333]
This would be useful to have both for the drop rates of quest items but also for journey search

https://github.com/Muehe/sqlua/commit/837895bd845b4dd6afa5ae6b38a72744e59011ff

@Muehe recently implemented it into his db tool, so we just need to add code to work with it in questie

**Comment by Gogo1951** [comment]
Drop rate data is really wildly in accurate. Let's table this, it's hard to create actionable data even if we incorporate the info.

**Comment by Yttrium-tYcLief** [comment]
We're finally getting around to this!

Due to our correction workflow, we feel it doesn't make sense to have item drop data be part of the regular itemDB. While drop rates could sit alongside each NPC record in the item DB, they would be overwritten by corrections.

We also, frankly, don't care about the drop rates of *every* item, we only care about the ones pertaining to quest objectives. So we're going to have separate, automatically-generated drop rate databases; one based on cmangos and one based on scraped wowhead data. The cmangos DB will be higher priority, but only contain items that cmangos believes drops *only* while on the quest ("quest item"), while Wowhead will fill in any gaps (for things like Murloc Eye which always drop but are an objective for the Westfall Stew quest, wowhead probably has more accurate drop data). Additionally, having Wowhead as a data source will be helpful for environments where we don't have cmangos data (like Season of Discovery and whatever comes after it).

Drop data will not determine whether Questie deems that an NPC drops that item or not; it will only be displayed as supplemental data on tooltips if Questie has already deemed that NPC drops the item. This way we still hold manual control and can correct instances where, for example, a rare spawn technically drops a quest item alongside the regular nearby mobs (and we don't want the rare spawn icons littering the map).
