### ISSUE TITLE
Teldrassil Quest: Crown of the Earth

### ISSUE THREAD

**Issue by x003** [AeroScripts/QuestieDev#240]
At the last part of this chain where you need to fill the Amethyst Phial in the Orcale Glade Moonwell questie says to go to the wrong place, The temple of the moon in Darnassus instead of The Oracle Glade (38, 34)

**Comment by Dyaxler** [comment]
I have personally checked these quests on a number of different toons and different servers. Again, if you're not on an English server then I can't help you. :(

**Comment by Dyaxler** [comment]
Disregard my previous comment... it might be related to the bad Astrolabe data. According to the Questie database the last step for Crown of the Earth is in Darnassus but because the zone data was bad, it was probably defaulting to some earlier values in your SavedVariables file. Darnassus was patched with a Hotfix for v3.1. Please test again.

>  ["Crown of the Earth"]={
  ["Fill the Crystal Phial and bring it back to Tenaron Stormgrip atop Aldrassil."]={0,3779547568},
  ["Bring the Partially Filled Vessel to Corithras Moonrage in Dolanaar."]={0,658982664},
  ["Fill the Jade Phial and bring it back to Corithras Moonrage in Dolanaar."]={0,3898559928},
  ["Fill the Tourmaline Phial and bring it back to Corithras Moonrage in Dolanaar."]={0,8875032},
  ["Fill the Amethyst Phial and bring it back to Corithras Moonrage in Dolanaar."]={0,172976144},
  ["Bring the Filled Vessel to Arch Druid Fandral Staghelm in Darnassus."]={0,1161253480},
 },

http://db.vanillagaming.org/?quest=935

**Comment by ZoeyZolotova** [comment]
The underlying issue here is that the [Vial of Blessed Water](http://db.vanillagaming.org/?item=5646) that you need for the quest [Crown of the Earth](http://db.vanillagaming.org/?quest=934) is also the objective of the quest [Felbound Ancients](http://db.vanillagaming.org/?quest=4441). The one needed for Crown of the Earth is acquired in northern Teldrassil, while the one for Felbound Ancients is acquired from The Temple of the Moon in Darnassus. 

Questie only has one of those locations (the one for Felbound Ancients) in its data:

  ["Vial of Blessed Water"] = {
    ["locations"] = {
      [1] = {21.0, 0.3939, 0.8433, 100.0}
    },
    ["locationCount"] = 1
  },

![crownoftheearth](https://cloud.githubusercontent.com/assets/22694317/20461732/ff03b0b4-af5a-11e6-95e0-2f7079db2cbd.png)

**Comment by AeroScripts** [comment]
We're currently in the process of overhauling the whole DB for 4.0. This is one of the many things that will be fixed once that reaches the master branch.
