### ISSUE TITLE
Quest levels are incorrect

### ISSUE THREAD

**Issue by Ghamarro** [AeroScripts/QuestieDev#246]
When I hover over an exclamation mark in the map, added there by Questie, I can see the quest level and the description just fine, but the quest level is sometimes incorrect. I checked some vanilla databases and verified that my realm, Kronos I, is actually blizzlike in terms of questing content, and they all gave me same result, so I'm guessing it's a bug or perhaps Questie's database is incorrect?

**Comment by Dyaxler** [comment]
Quest levels are pulled from Questie's database which was built using: http://db.vanillagaming.org

Not all databases contain the same info since it's been passed down, around, interpreted from numerous other emu projects. Even WoWHeads data isn't the same anymore so it's not 100% accurate. You can use Questies quest level filters to force a quest to be hidden or shown depending on character level. You can read up on the command line options and FAQ here:

https://github.com/AeroScripts/QuestieDev/blob/master/Readme%20%26%20FAQ.txt

**Comment by Ghamarro** [comment]
So is questie supposed to show the quest's required level or the actual level of the quest when hovering over the mark on the map? I remember this quest for instance [http://db.vanillagaming.org/?quest=6548](http://db.vanillagaming.org/?quest=6548) which says "level 12" when you hover over it in-game, but it is shown as a 18 quest in db.vanillagaming.com although with 12 as the required level. Is there a way to filter out map quest markers based on the actual quest level, not the required minum level?

**Comment by Dyaxler** [comment]
>  [1917763378]={
  ['name']="Avenge My Village",
  ['startedType']="monster",
  ['finishedType']="monster",
  ['startedBy']="Makaba Flathoof",
  ['finishedBy']="Makaba Flathoof",
  ['level']=12,
  ['rr']=178
 },

Info in the database is correct. Level 12 is the "minimum" level you have to be in order to obtain the quest. db.vanillagaming.org says as well:

> 
    Level: 18
    Requires level: 12
    Side: Horde
    Start: Makaba Flathoof
    End: Makaba Flathoof
    Sharable

On db.vanillagaming.org - if you hover over Level: 18 under Quick Facts it'll show you the min - mid - max color values which is 15 - 19 - 22. In other words you can get the quest at level 12, the quest is RED from level 15-18, GREEN from level 19-21 and GREY from level 22 on up. Most sites say to do a quest before it turns green for maximum XP and reward. Not sure how db.valillagaming.org assigns these color values because I could swear that quests turn yellow then green. :)

**Comment by Dyaxler** [comment]
According to WoWHeads LIVE retail data this same quest has a difficulty color key... slightly different values but close enough that the suggested level is around 18 for this quest to be easy for most players. Personally, I like to keep things a bit harder so I generally do a quest when it turns Orange.

![capture](https://cloud.githubusercontent.com/assets/17400948/15449361/9da45ef0-1f30-11e6-8f45-0a136f9198d5.JPG)

**Comment by Muehe** [comment]
MinLevel and QuestLevel are actually [two](https://github.com/cmangos/issues/wiki/Quest_template#minlevel) different values in the core. Quick ingame test showed that QuestieTracker shows correct quest level (18) and the colors behave like wowhead shows.

**Comment by Ghamarro** [comment]
I guess I phrased myself a bit incorrectly. I now understand that it's not a bug that it shows MinLevel instead of QuestLevel, but I'm still at a loss about if there's a way to make the quest markers not appear until the quest would be yellow for me, or, in other words, when I'm 2 levels below QuestLevel, instead of the way it is now where the quest makers appear on the map when I am at MinLevel.

**Comment by Ghamarro** [comment]
Would you consider adding the QuestLevel in addition to just the MinLevel into the info box you get when hovering over quest markers on the map? That would be really helpful for people like me who are aiming to do only yellow quests, so that we wouldn't have to alt tab into db.vanillagaming.org to check it before taking it. As the marker doesn't reappear on the map if you take it in-game to check the QuestLevel and then abandon it if it's orange or red, it would be such a chore to make sure you don't accept orange or red quests.

**Comment by Muehe** [comment]
I think this would require a DB update since only MinLevel is in Questie data and real quest level is aquired when a quest is active by using GetQuestLogTitle(). But should be possible...

**Comment by ZoeyZolotova** [comment]
I've never worked with wow addons before but I've updated all the quests with a quest level and made the map tooltips use them. #276

**Comment by Schaka** [comment]
Fixed in https://github.com/AeroScripts/QuestieDev/commit/4beb96575f1bd3ae311350e79e10885053302929
