### ISSUE TITLE
API

### ISSUE THREAD

**Issue by ShervinNejad** [AeroScripts/QuestieDev#2490]
Thanks for a great addon!
Is there any way to grab data from your database so I can use it in my own addon?
I need to get the quest level from questID.

In the beta, I could use:

**local questID = 12345
local questLevel = QuestieDB.questData[questID][5]**

but it doesn't work anymore, since you made the database local.

Thanks!

**Comment by Muehe** [comment]
Hello there.

We introduced a module loading system a while back so as to not pollute the global namespace with our stuff, and there is also a wrapper function to access the DB. This should work when Questie is enabled:

```lua
local QuestieDB = QuestieLoader:ImportModule("QuestieDB")
local quest = QuestieDB.GetQuest(12345)
local questLevel = quest.level
```

See [here](https://github.com/AeroScripts/QuestieDev/blob/2ea895c244865ade6135215be4f36782f9055290/Database/QuestieDB.lua#L533-L875) if you want to know how the `quest` object is structured.

Notice that [the comment](https://github.com/AeroScripts/QuestieDev/blob/2ea895c244865ade6135215be4f36782f9055290/Database/QuestieDB.lua#L568) says the field is called `questLevel`, but it's called `level` if you read the [actual code](https://github.com/AeroScripts/QuestieDev/blob/2ea895c244865ade6135215be4f36782f9055290/Database/QuestieDB.lua#L714). Not sure how far those comment/code inconsistencies go.

I'll close this issue, since it's not something we need to fix, but feel free to comment here if you have more questions about this.

**Comment by ShervinNejad** [comment]
Thanks a lot for the help!
It works fine now :)
