### ISSUE TITLE
Reducing the frequency of 'stupid questions'

### ISSUE THREAD

**Issue by winny-** [AeroScripts/QuestieDev#256]
I've noticed there are a lot of 'stupid questions' -- questions answered in the FAQ. I have some ideas on how to reduce the frequency of these questions:

I suggest adding a `CONTRIBUTING.md` that has a reminder to read `Readme & FAQ.txt` before opening an issue or pull request. This a header will appear while somebody is trying to file a new issue.

More information here https://github.com/blog/1184-contributing-guidelines

Another idea I had would be to markdown-ify `Readme & FAQ.txt` so it reads nicer to people uncomfortable with plaintext formatting/layout.

**Comment by Ghamarro** [comment]
Is "why does Questie show enemy faction quests on the map?" a stupid question?

**Comment by Muehe** [comment]
@Ghamarro No it isn't. However there are some issues regarding available quests, but you only see them when you remove the "is:open" from the search bar or click through the closed issues.

I think the reason for this bug is that [RequiredRaces](https://github.com/cmangos/issues/wiki/Quest_template#requiredraces) isn't always correctly set in server DBs. The quest will have 0/255 set while it is only given by NPCs with differing [FactionAlliance/FactionHorde](https://github.com/cmangos/issues/wiki/Creature_template#FactionAlliance) flags, i.e. quest is "available" to both factions but one of them can't talk to the quest giver because he is hostile to them.

This could be accounted for by the extractor. According to @Dyaxler somebody was in the process of building a new one, but I am unsure whether that is still in progress or abandoned.
