### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by KevinTyrrell** [AeroScripts/QuestieDev#262]
Thought it'd be better to post one issue instead of multiple:

**Issue 1:** Questie not displaying in instances / raids
    I cannot locate an option that allows Questie to be toggled off or on when inside of a dungeon. I've been on many twitch streams where the streamer is having the same problem. I completely agree with them that it is not easy to find.

**Issue 2:** Questie frame prevents click-through while opaque
    When hidden inside a dungeon, the questie frame can still be clicked through. Meaning, if the questie quest tracker frame is hidden, then you click on where it is and drag as if you want to rotate your camera, you will be unable to and it will appear like your drag had no effect. I am not sure but I BELIEVE yo can also move the questie frame while it is not visible.

**Issue 3:** 2/3 of Quests do not have map markers or arrow destinations. 
    This is fine, as I know how many quests there are in-game and how complicated it might be to implement more, but _teach the users how to add them ourselves_. Crowd source this part. For example, let's say I'm leveling up and I encounter a quest without a marker. I would fix it in that case and likely want to reupload it so others have it for their Questie. Please reply with how we can add our own markers / arrows (the arrows are likely the most important).

**Issue 4:** Users cannot lock or resize Questie frame.
    Implementation should be made to fix this. 

Suggested additions:
- Questie quest tracker frame should open quest log and go to the quest that the user right clicked on the Questie frame. It'd be a big help. For example, user sees the quest [34] Gnome Improvement on Questie. User wonders exactly why he wants a silver bar. User right clicks the quest on the Questie quest tracker frame. His quest log then opens up to that quest. 

Thank you.

**Comment by Muehe** [comment]
> Thought it'd be better to post one issue instead of multiple

Normal procedure is one issue per problem/suggestion. Makes it easier to track if a problem is still existing, as the others will be closed.

> **Issue 1:** Questie not displaying in instances / raids
I cannot locate an option that allows Questie to be toggled off or on when inside of a dungeon. I've been on many twitch streams where the streamer is having the same problem. I completely agree with them that it is not easy to find.

The big button on the world map frame is not easy to find? Ok. Anyway, instance maps are not a thing because there simply are none in the Blizzard map "addon", and relocating the notes on Cartographer to match instance maps is a pain in the a**. If you want an easier way of toggling Questie on and off you can create the following macro: `/script Questie:Toggle();`

> **Issue 2:** Questie frame prevents click-through while opaque
When hidden inside a dungeon, the questie frame can still be clicked through. Meaning, if the questie quest tracker frame is hidden, then you click on where it is and drag as if you want to rotate your camera, you will be unable to and it will appear like your drag had no effect. I am not sure but I BELIEVE yo can also move the questie frame while it is not visible.

This sure sounds like you use an older version of Questie. When you use `/questie settings` the last line should show your Questie version. 3.1 is the current version.

> **Issue 3:** 2/3 of Quests do not have map markers or arrow destinations.

Again, sounds like an older version. Questie should show objectives for at least ~90% of quests. If you have Questie 3.1, maybe your settings are wrong or you have the same problem as #261 

> This is fine, as I know how many quests there are in-game and how complicated it might be to implement more, but teach the users how to add them ourselves. Crowd source this part.

Right now Questie locations are extracted from server data, so you'd "only" need to find the data in the server files/db and add it to the extractor. Also, crowd sourcing this would open a door to abuse and poorly researched data.

> For example, let's say I'm leveling up and I encounter a quest without a marker.

That's what the issue tracker is for basically.

> I would fix it in that case and likely want to reupload it so others have it for their Questie. Please reply with how we can add our own markers / arrows (the arrows are likely the most important).

The arrow points to the nearest map marker it can find (or the minimap icon you last clicked I believe). So you only need correct markers.

Data for this is stored in the [!Questie/Database/](https://github.com/AeroScripts/QuestieDev/tree/master/!Questie/Database) folder. Coordinates are stored in a [0, 1] format, so (0.504, 0.73) would be position (50.4, 73.0) in Cartographer [0, 100] format.

You are of course welcome to fork Questie and make pull requests from your fork to it. If you have done some decent PRs I'm sure the repository owner would give you push rights, as Questie development has been stalled since about Nost shutdown (last commit was May 18th).

> **Issue 4:** Users cannot lock or resize Questie frame.
Implementation should be made to fix this.

Which frame? The tracker?

> Suggested additions:

Good idea, but like I said, currently no one is developing. If you don't want to get into that yourself, create a separate issue marked "feature request" and hope that someone will pick it up in the future.

**Comment by KevinTyrrell** [comment]
Well. I haven't been that embarassed in awhile. I should be ashamed as a dev myself that the issues I was experiencing were caused by a lack of updating. I guess I must have an ANCIENT version because of this: 

![svzoudy](https://cloud.githubusercontent.com/assets/12791400/16561095/40616f14-41ac-11e6-904b-d94562e5e5c9.png)

My version is **v2.0.10 BETA** LOL. I'm really sorry for wasting your time. Sad to see development has stopped on this amazing addon. I take it you and the remaining developers are not playing on Kronos, and instead on other projects? 


Anyhow, thank you very much for you reply. I will try the new version and report back with any concerns I might have. Most likely though with my rudementary knowledge of LUA and this addon being discontinued, any improvements I would submit here wouldn't likely be implemented. Again, thanks for the assistance.

**Comment by Muehe** [comment]
I'm no real Questie dev, just PR'd one fix. I just try to help with little problems here in the issues if nobody does it before me. But the Devs didn't die, so if you make a PR I'm sure they'll look at it. Just no active development right now.

Btw. I was developing my own quest addon and am in the process of merging it with ShaguQuest. If you want you can download a prerelease [here](https://github.com/shagu/shaguquest/releases), feedback is always welcome. 😄 And it is compatible with Questie, so you can use both of them together.

**Comment by KevinTyrrell** [comment]
Thanks a lot. I will definitely check your project out. One thing to add. I've downloaded the updated version of questie and I cannot locate the minimap icon that you spoke of. I've swapped out my WTF folder and one still does not appear. In this updated version, it does not appear that I can change the location of the questie quest tracker. Most importantly, I cannot find a way to manually complete quests. In Questie 2.0 beta, I could type `/questie complete Favor for Krazek` and it would complete that quest. Do I need to call the function `/script Questie:Complete();` or something? 

Thanks!

**Comment by Muehe** [comment]
I meant the minimap icons for quest objectives. If the quest is tracked and you click on one of them, the arrow will point to the nearest point it can find for that objective.

Arrow and tracker can be moved with Ctrl+Shift+Click. Quests are marked as finished by Shift+Clicking them on the world map.

There is an [FAQ](https://github.com/AeroScripts/QuestieDev/blob/master/Readme%20%26%20FAQ.txt).
