### ISSUE TITLE
Quests from different factions

### ISSUE THREAD

**Issue by grinsteindavid** [AeroScripts/QuestieDev#274]
It is normal to see horde quests in the map ( cartographer ) when I'm alliance? 

wow 1.12

**Comment by Muehe** [comment]
Yes, kind of. This happens due to some quests having the wrong mask set in [RequiredRaces](https://github.com/cmangos/issues/wiki/Quest_template#requiredraces), which the current extractor does not seem to account for. Technically speaking you could acquire them if you were not hostile towards the Horde/Alliance NPCs giving those quests (which never happens of course).
