### ISSUE TITLE
"The Princess Trapped" - quest not showing up on map.

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#342]
quest not showing up on map.

http://imgur.com/a/SC0uA

**Comment by Elektropole** [comment]
Yes, I have the same problem it doesn´t show on map for new Quests and "Toggle Questie" dont work.
Older Quest i can toggle and are shown.

**Comment by Dyaxler** [comment]
Any "Quest Database" issues aren't going to be fixed in the current versions of Questie anymore. Aero is busy working on Questie V4.0 and it'll have a BRAND NEW database based on the servers quest database so it should be 100% accurate. :)

The current database is really old and has been cobbled together over a period of several years. Not everything from older Private Servers were always correct compared to the newer ones that are out today.

**Comment by AeroScripts** [comment]
This may actually be an unrelated bug, not a problem with the db, since at least "The princess is trapped" has quest data in the DB:
  ["Mote of Myzrael"] = {
    ["drop"] = {
      ["Drywhisker Surveyor"] = 1020,
      ["Drywhisker Digger"] = 1773,
      ["Drywhisker Kobold"] = 2489
    }

Also @Elektropole, "doesn´t show on map for new Quests "Toggle Questie" dont work" sounds like a different issue also

**Comment by Dyaxler** [comment]
I really think the issue here is that "object" type's aren't supported properly.

` [88971736]={
  ['name']="The Princess Trapped",
  ['startedType']="object",
  ['finishedType']="object",
  ['startedBy']="Shards of Myzrael",
  ['finishedBy']="Iridescent Shards",
  ['level']=30,
  ['questLevel']='37'
 },`

I vaguely remember that one of the steps in Captain Sander's Hidden Treasure wasn't working either. A quick look confirms it that his Footlocker is a game object.

I seem to recall doing research on this months ago and that in Vanilla you couldn't "interact" programmatically with game objects. It was hard coded in the client. BC was the first expansion that allowed you do "do things" with game objects.

**Comment by Dyaxler** [comment]
Here is another way of looking at it... when you're running an addon that keeps track of Herbs or Ore nodes... the addon doesn't record it's location until you loot from it. You can't simply walk up to a node and right or left click on it and expect your addon to record the location. There is no "feed back" confirmation that you've actually interacted with the game object. So "static" quest objects - I.E. 3D Objects in the game world can't be manipulated. Same goes for folks who have attempted to add "sparkles" to ore, herb nodes and quest objects. However, if you can get an "item" from a 3D object then you can record it's location... ore, herbs, looted quest object. But you can't record a quest or verify that you've interacted with a quest to trigger an event unless that object gives you something.

**Comment by Dyaxler** [comment]
Ha! Perfect example... "Wanted:" posters. They don't show up on the World Map as Quest Givers. Hogger... if I can figure out why that isn't showing up then this one can be fixed as well.

**Comment by Dyaxler** [comment]
Still investigating these issues...

**Comment by Dyaxler** [comment]
Can someone tell me the exact location of this Quest Starter? Please use this macro in game while standing as close to the Quest Starter as possible. Then post a screen shot.

`/script SetMapToCurrentZone() local x,y=GetPlayerMapPosition("player") DEFAULT_CHAT_FRAME:AddMessage(format("%s, %s: %.1f, %.1f",GetZoneText(),GetSubZoneText(),x*10000000000000,y*10000000000000))`

**Comment by Dyaxler** [comment]
I think I may have narrowed down this issue...

Quest Starters can only be started by a ['startedType']="monster" - this is somewhat misleading because NPC's who are Quest Givers are also referenced as a monster and an entry exists in the monsters.lua database file. However, if you're ON a quest and the next step is a follow up quest by a different title, then the can be a ['startedType']="object".

My test case is:

```
 [2250606541]={
  ['name']="Wanted:  \"Hogger\"",
  ['startedType']="object",
  ['finishedType']="monster",
  ['startedBy']="Wanted Poster",
  ['finishedBy']="Marshal Dughan",
  ['level']=5,
  ['questLevel']='11+',
  ['rr']=77
 },
```
There is no location entry for ['startedBy']="Wanted Poster" so I added one:
```
  ["Wanted Poster"] = {
    ["locations"] = {
      [1] = {37.0, 0.2455, 0.7470, 100.0}
    },
    ["locationCount"] = 1,
    ["faction"] = 1
  },
```
Then I change   ['startedType']="object"  --> ['startedType']="monster" and bingo - the quest marker showed up on the map. :)

**Comment by Dyaxler** [comment]
So looking at The Princess Trapped quest. There is a location entry in the database but again... the quest is flagged as: ['startedType']="object" --> changing this to 'monster' should resolve this bug.

Please give this a try.
```
 [88971736]={
  ['name']="The Princess Trapped",
  ['startedType']="monster", <--- change this to monster
  ['finishedType']="object",
  ['startedBy']="Shards of Myzrael",
  ['finishedBy']="Iridescent Shards",
  ['level']=30,
  ['questLevel']='37'
 },
```

**Comment by Dyaxler** [comment]
Added to v3.66
https://github.com/AeroScripts/QuestieDev/releases/latest
