### ISSUE TITLE
Show the level required to start quests rather than recommended level?

### ISSUE THREAD

**Issue by ShaunDreclin** [AeroScripts/QuestieDev#344]
Really annoying not being able to tell if I can pick up a quest or not. Would like to set max quest level to 0 above my level and only see markers for quests I can actually pick up.

**Comment by Dyaxler** [comment]
I don't understand... you want the filter to filter quests at the "Required Level" or the "Recommended Level"... two totally different values.

I think this feature was broken when someone added an additional value to Quests in the database. I haven't had time to review that part of the code but it's on my ToDo list if Elysium would stop F'ing with the servers.

**Comment by ShaunDreclin** [comment]
I want to filter quests based on required level and completely ignore recommended level.

**Comment by SalviaSage** [comment]
This is a great idea. Currently Questie filter works based on recommended levels. It would be nice to have an option to also see the quests required level.

Please add this feature. 

The more options the users have the better this addon becomes.

**Comment by Dyaxler** [comment]
In Vanilla there were only two options... Quest Level and Minimum Level. During the months leading up to Burning Crusade, WoW Head started showing the "Recommended Level". I have no idea how they came up with this number. In the current version of the Quest Database there are only two values, raw quest level and minimum level. I can only "key" off one or the other. Several versions ago the minlevel and maxlevel filters were using the Quest Level to filter quests and the min level wasn't in the database. A contributor added this value and broke the minlevel maxlevel filters when these functions were changed to key off of min level rather than quest level. These filters are OFF by default. You can now adjust how many levels above and below by setting the setmaxlevel and setminlevel.
```
'questie maxlevel' <-- turns filters on or off
'questie minlevel'' <-- turns filters on or off
'/questie setmaxlevel #' <-- replace # with the desired level you want filtered
'/questie setminlevel#'<-- replace # with the desired level you want filtered
```
This has been fixed in the new version.
https://github.com/AeroScripts/QuestieDev/releases/latest

Don't forget to read the readme and the changelog or run the '/questie' command in game for options to customize Questie.

**Comment by ShaunDreclin** [comment]
Thank you!!
Tested and it works wonderfully now! ❤️

**Comment by Dyaxler** [comment]
Awesome! Thanks for the confirmation.
