### ISSUE TITLE
Quest Log Chat Link

### ISSUE THREAD

**Issue by SalviaSage** [AeroScripts/QuestieDev#365]
On some quest tracker addons when you shift click on a quest objective while the chat tab is open, the quest objective becomes printed into the chat tab. Useful for talking to other players about quests.

Can you add this feature to questie's quest tracker?

**Comment by Dyaxler** [comment]
Yeah, this is on of those features that would be "nice to have". I'll look into it but no promises.

**Comment by SalviaSage** [comment]
Thanks Dyaxler.

**Comment by Dyaxler** [comment]
If the chat window is open and you Shift + Click the quest the title of the quest will appear in your chat entry. However, it won't create a "clickable" link like you can with items commonly showing in trade chat.

Unless you know of a mod that does it - then do tell. I can't seem to find one.

**Comment by Muehe** [comment]
https://github.com/shagu/shaguquest/blob/master/ShaguDB_GUI.lua#L623-L628

**Comment by Dyaxler** [comment]
I have to do some fancy gsub to filter out the quest levels and just display the Quest Title but I get this error when I try it and the line of code I'm using:
```
ChatFrameEditBox:Insert("|cffffff00|Hquest:0:0:0:0|h["..gsub(this:GetText(), ".*%]%s(.*)", "%1").."]|h|r");
```
![image](https://cloud.githubusercontent.com/assets/17400948/22187602/460fbc16-e0be-11e6-9bac-6fa8453ff6cd.png)

**Comment by Muehe** [comment]
```lua
if not ChatFrameEditBox:IsVisible() then
    ChatFrameEditBox:Show()
end
ChatFrameEditBox:Insert("|cffffff00|Hquest:0:0:0:0|h[".."Some random text that isn't necessarily a quest name".."]|h|r")
```

The link that is created by this checks the quest log for a quest with this name and if one is found, it shows the quest progress and objective text.

**Comment by Dyaxler** [comment]
@SalviaSage - this feature requires another Mod in order to get the links to work right. This type of feature wasn't introduced to WoW until BC. If I inserted a "fake" hyperlink colorizer for quests then yes, you'll see the familiar bracketed QuestTitle and it's clickable but it results in an error unless you have this other Mod installed. ShaguDB does this already. It comes with ShaguQuest and you can run ShaguDB along side Questie just fine as Muehe does.
