### ISSUE TITLE
Quest Tracker Toggle Button

### ISSUE THREAD

**Issue by SalviaSage** [AeroScripts/QuestieDev#366]
So, how come we need to reloadui when we type /questie tracker to enable and disable the quest tracker.

I request that a toggle button be added to the quest tracker header where it says QuestLog Status so we can easily hide or show the quest objectives. 

Also. Earlier I accepted a quest and the quest was not automatically added to the quest tracker.
These 2 features that I talked about exist in some other quest addons and I would like them implemented in Questie as well.

**Comment by Dyaxler** [comment]
> So, how come we need to reloadui when we type /questie tracker to enable and disable the quest tracker.
There are some elements in the vanilla client that can only be "turned on" or "reset" by a ReloadUI. The tracker, header, and listdirection will only work after a ReloadUI. 

> I request that a toggle button be added to the quest tracker header where it says QuestLog Status so we can easily hide or show the quest objectives.
So wait, you want to be able to click on the QuestieTracker Header and make the list disappear, collapse or minimize like it does in Monkey Quest?

> Also. Earlier I accepted a quest and the quest was not automatically added to the quest tracker.
> These 2 features that I talked about exist in some other quest addons and I would like them implemented in Questie as well.
Sounds like you're using the Default WoW QuestLog. Its VERY limited so rather than us try to make it work for Questie the original Dev team opted to rely on a more popular QuestLog mod - EQL3 or Enhanced QuestLog. Use that instead. It'll "auto track" quests.

**Comment by SalviaSage** [comment]
> So wait, you want to be able to click on the QuestieTracker Header and make the list disappear, collapse or minimize like it does in Monkey Quest?

Yes, exactly like in Monkey Quest. Since we have to /reloadui to disable the whole quest tracker. The user should have the option of simply hiding the quest tracker with a button on the quest header or a with a slash command.

What if he doesnt want a big list of 20 quests on his screen when he is doing a BG?

> Sounds like you're using the Default WoW QuestLog. Its VERY limited so rather than us try to make it work for Questie the original Dev team opted to rely on a more popular QuestLog mod - EQL3 or Enhanced QuestLog. Use that instead. It'll "auto track" quests.

I was using the extended quest log and the "track quests" button on top of the window was green. But I noticed the quest was not added to my list when I picked it up. I don't know if this is a problem or not. I just noticed it earlier and I want to confirm questie will automatically add all quest objectives to quest tracker upon taking them. 

I know quests can be added individually or the whole category by shit_clicking them on the extended quest log, but it should do it automatically.

**Comment by Dyaxler** [comment]
If you UN-track all your quests it will hide the tracker... but I'll look into maybe adding a minimize feature to the tracker *if* the user is using the Header feature. No other way around it. I mean I could program around it but whats the point? Aero is working 4.0 and it's a whole re-write anyway. :)

Extended QuestLog will add quests automatically upon pickup. It works because it's always worked with and without Questie. We don't include our own version of EQL3 but simply hook into some of it's functions when it's present.

Quest issues or weird issues are usually caused by a bad cache. Deleting the contents of the WDB folder usually fixes those kinds of issues. There is wide spread interpretation of "server side DB's" in the Vanilla WoW community. Not all servers are alike so if you hop from Elysium to Kronos or some other project, clearing your cache is a must and if AddOns store data base on server DB's... you'll have to clear those as well.

**Comment by Dyaxler** [comment]
... by the way. No promises. :)

**Comment by Dyaxler** [comment]
OK, this was MUCH easier than I thought it would be... new release:
https://github.com/AeroScripts/QuestieDev/releases/latest
