### ISSUE TITLE
Remove Questie Icons on Minimap Borders

### ISSUE THREAD

**Issue by orwellnotsowell** [AeroScripts/QuestieDev#370]
I'm posting here as Dyaxler suggests.

First of all, thank you all for spending your precious time on this awesome addon.

I have a suggestion.

Questie adds icons to the borders of minimaps when quest items are far away and outside of minimap range.

This clutters minimap borders especially when you have lots of quest. 

It's usually not productive to move according to minimap icons so almost everyone open their big map to see where to go next.

**Comment by Dyaxler** [comment]
Thanks for moving the thread. I'll look through my old source code and see if I can't find my original changes. You can do the same here on GitHub. Just look through my old Commits if you can't wait.

So you only want to see quest givers and objectives within mini map radar range?

**Comment by Dyaxler** [comment]
OK, update... in my attempts to trim down memory usage I've gone with the model of only executing functions when they are absolutely needed. So no more forcing the tracker or the map notes to update on each OnUpdate(elapsed) approach. Which means that I'm not going to add a feature that will detect items outside the mini maps range and hide them automatically. The distance calculations alone would counter act my efforts to trim down memory. I don't see an easier way to doing it. We're already filtering quest markers outside the players current zone. However, Aero recently added a couple of new slash toggles...

![image](https://cloud.githubusercontent.com/assets/17400948/22276794/0da82e4a-e26b-11e6-9203-b1386be4f700.png)

These will accomplish what you're after; DE-clutter the mini map. You can toggle either. Toggling both will turn off all Questie markers off just the mini map. Not the World map. I changed it slightly to always show the "Finisher" icons...  Gold ?. That to me should be the only icon that appears on the mini map from a minimalist viewpoint.

For others reading this... these are optional features and not turn on by default.

**Comment by orwellnotsowell** [comment]
"So you only want to see quest givers and objectives within mini map radar range?"
-Yes

I didn't understand your second post. Should I use /hideminimap or /hideobjectives?

**Comment by Dyaxler** [comment]
The new toggles are your only compromise unfortunately. Constantly rerunning the map draws are expensive cycles to run. There can be hundreds of markers on the map depending on zone and quest combinations. I'd have to force a refresh for each and every marker on the mini map 10x per second otherwise. Any slower and you'd notice a flicker and people don't like it when their icons flicker. :D

**Comment by Dyaxler** [comment]
Sorry I re-read that description and it's a bit miss-leading...

/questie hideminimap - doesn't actually hide the mini map. ha! I should change that. It only hides Quest Giver icons... the yellow ( ! ) markers. If a quest is finished it'll still show it because generally there are only a few at a time per quest session.

/questie hideobjectives - well that one should be fairly self-explanatory. :)

**Comment by orwellnotsowell** [comment]
So basicly you're not offering any solution to my first post.
Hmm...

**Comment by Dyaxler** [comment]
I did offer you a solution. It's not exactly what you wanted though but it would get the Objective icons off your mini map which is the largest contributor to clutter. We simply can't implement a feature where we have to check the distance between the player and every map object in the zone. It can be done sure but it would cause a lot of game stuttering and Garbage Collection would be through the roof. The QuestieArrow already contributes to that. I've been trying to reduce the memory footprint - not the overall size of the addon package but the amount of memory it consumes and then recycles.
