### ISSUE TITLE
Questie background adjustment optimization

### ISSUE THREAD

**Issue by SalviaSage** [AeroScripts/QuestieDev#373]
Hi. Thanks for re-introducing the automatic adjustment of the quest tracker background. I can say that it works without any errors.

1) However, I have noticed that after logging out and logging back in, the questie background always extends down to the very bottom of the screen, and after tracking and untracking a quest it updates and fixes itself, but upon entry it extends down all the way.

Also earlier you said:
> If the chat window is open and you Shift + Click the quest the title of the quest will appear in your chat entry. However, it won't create a "clickable" link like you can with items commonly showing in trade chat.

2) It only does this for the quest log, when you shift click the QUEST TRACKER. the tomtom arrow comes up instead. So can we also make ctrl+shift click on a quest tracker quest to link it in the chat bar?

**Comment by Dyaxler** [comment]
1.  I noticed this when testing this morning. Just finished a hot fix for the dynamic height refresh issue.


  1.  In Vanilla WoW there was no way you could Shift+Click a quest. ShaguQuest does it but it will only show you a Quest Description when you’re actually on the Quest. If you’re not, like if someone links a quest in chat, it’ll tell you that you aren’t on the Quest. Instead of writing in a whole other feature to mimic what ShaguQuest has, I opted for a bracketed Quest title to make it stand out more. If you attempt to ‘colorize’ text without going through the Blizzard Hyperlink API it will boot you from the server. Clicking a quest in the quest tracker with or without the shift key will result in the QuestieArrow appearing and disappearing. This is by design.

**Comment by Dyaxler** [comment]
Fix in latest release... zip file updated:
https://github.com/AeroScripts/QuestieDev/releases/latest
