### ISSUE TITLE
Completing Quests May Not Remove Quest Markers

### ISSUE THREAD

**Issue by ThiconZ** [AeroScripts/QuestieDev#381]
When the quest in Desolace named Vaharriel's Search ( http://www.wowhead.com/quest=1437/vahlarriels-search )  is completed and the next part ( http://www.wowhead.com/quest=1438/vahlarriels-search ), with the exact same name is accepted, the quest complete marker does not go away. This makes it so if the marker is moused over for any reason an error is displayed.

![image](https://cloud.githubusercontent.com/assets/6924950/22359400/ea02f348-e414-11e6-8f0a-079fc51da343.png)

**Comment by Dyaxler** [comment]
I had a feeling that would start happening. There is an event or function firing too late. This was resolved by running most of the bloody functions full throttle. It's not "Quest" specific. I'll try throttling the finishAndRecurse() function by a 1/2 second and see if that helps prevent these kinds of issues.

I don't want to add a nil check because then people will be too lazy to complain about it. :)

**Comment by ThiconZ** [comment]
Updated issue title to better reflect the actual issue.

**Comment by Dyaxler** [comment]
I found a typo... I didn't see this error until I turned off ALL my mods. "bad tester!"

Somehow one of my mods was fixing this issue or over-writing it's "bad" attempt and fired successfully on my dev box.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
