### ISSUE TITLE
/questie hideminimap - doesn't work  on newest version

### ISSUE THREAD

**Issue by kev41** [AeroScripts/QuestieDev#389]
/questie hideminimap - doesn't work  on newest version

**Comment by Dyaxler** [comment]
Which build are you using? Version please? Release? Latest commit?

**Comment by kev41** [comment]
Latest commit, downloaded it today

**Comment by kev41** [comment]
getVersion= 3.69

**Comment by Dyaxler** [comment]
I'll look into it...

**Comment by SalviaSage** [comment]
I just tested this. 

For me, when I type /questie hideminimap
the swords get hidden on the minimap same as typing /questie hideobjectives

the exclamation marks and question marks are still on the minimap.

I'm sure it is supposed to hide the exclamation marks and question marks instead.

**Comment by Dyaxler** [comment]
You're right - it was broken. The new clustering code transformed the logic flow so I had to redo it. For some reason we didn't catch it in testing. It's pretty obvious but then again, most of us just pay attention to doing quests rather than sitting in a city someplace toggling options in the various states just to see if it's functioning. Kudos to you for pointing it out! Thank you! And now after re-working the entire logic flow... my brain is about to explode trying to compensate for most if not all conceivable combinations.

Here is the expected behavior for the MINI MAP only that I'll be putting into the next release:

>             -- If we aren't showing all quests (*showquests*) and we aren't tracking a quest then
>             -- hide untracked objectives from mini map. Quest starters within the players default
>             -- level range or user defined filters will always be displayed. *hideminimap* and
>             -- *hideobjectives* are optional toggles not on by default.
>             ---------------------------------------------------------------------------------------
>             -- *hideminimap* = hides mini map icons regardless of *showquests* toggle.
>             -- *hideobjectives* = hides all objectives regardless of *showquests* toggle.

Here is the expected behavior for the WORLD MAP only that I'll be putting into the next release:

>             -- If we aren't showing all quests (*showquests*) and we aren't tracking a quest then
>             -- hide untracked objectives from world map. Quest starters within the players default
>             -- level range or user defined filters will always be displayed. *hideminimap* and
>             -- *hideobjectives* are optional toggles not on by default.
>             ---------------------------------------------------------------------------------------
>             -- *hideobjectives* = hides all objectives regardless of *showquests* toggle.

NOTE: Due to the nature of the clustering code we CANNOT hide the Quest Starters so don't ask. If a cluster group contains a stack of Quest Starters AND a Finisher, then the finisher icon will represent that stuck and be listed first UNLESS you have *showquests* off and you're not tracking the finished quest. Only then will the icon that represents the stack will turn into an "available" quest icon. Make sense?

Although, I could be wrong about hiding Quest Starters. Zoey might jump in here and clarify for us. I still don't have my mind wrapped around Zoey's amazing work on the clustering code!

**Comment by ZoeyZolotova** [comment]
@Dyaxler should be pretty easy to hide available quests. Just tell me what the command should be and I can do the rest.

**Comment by kev41** [comment]
Next release doesn't mean latest commit right? I updated today, still can't hide minimap objects/quests with the command.

**Comment by ZoeyZolotova** [comment]
@kev41 Dyaxler has his changes in his private repo.

**Comment by ZoeyZolotova** [comment]
@kev41 Though if you like, you can try [this branch on my public repo](https://github.com/ZoeyZolotova/QuestieDev/tree/ItemQuestStarters) where I made a similar fix, though it does also include some experimental changes, but it should be stable enough.

**Comment by Muehe** [comment]
> Next release doesn't mean latest commit right?

@kev41 That's right. You can just download the whole repository instead of a release and copy the `!Questie` folder out of it, since there is no special release process involved.

**Comment by kev41** [comment]
@Muehe yeah thats what I do always for questie :)

**Comment by Dyaxler** [comment]
I've had to re-write this logic 3 times already. I'm almost afraid to commit it before we finish with the other stuff we've been working on. Takes a little longer to make a commit to master when you're collaborating with others.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
