### ISSUE TITLE
Some nil errors with newest modui version

### ISSUE THREAD

**Issue by johnnybgood89** [AeroScripts/QuestieDev#391]
Some nil errors with newest modui version. So if you can check it out

http://imgur.com/gxFPx8c

**Comment by johnnybgood89** [comment]
After updating questie, now its good.

**Comment by johnnybgood89** [comment]
Get error again, some arrow lua... in the chat , its not gamebreaking

**Comment by Muehe** [comment]
Sorry, but we need the error message for us to be able to help. 

I'd recommend you install ImprovedErrorFrame. It's an addon that lets you copy&paste the error messages from a window, which you can view using a minimap button (shows only if there were any errors). If there is more than one error, post the first one, the others are probably caused by it.

[ImprovedErrorFrame.zip](https://github.com/AeroScripts/QuestieDev/files/742446/ImprovedErrorFrame.zip)

We need the exact new error message, or at least the line and file (*e.g.* `QuestieTracker.lua:1033` *in the screenshot you posted*), or we this will be near impossible to fix. Also information on how to reproduce would be welcomed. From your screenshot I guess they happen on login?

**Comment by johnnybgood89** [comment]
Ok thanks , I have that addon but didnt use it yet.
Usually they happen on some time after login.

Same thing happens with addon enemyFrames

**Comment by Muehe** [comment]
A few other things you could try:

1. Delete the `Cache` (if present) and `WDB` directories from your World of Warcraft directory. They tend to cause issues upon switching servers (don't worry, this will not delete your settings, they are in the `WTF` directory).
2. Disable all other addons (or at least enemyFrames) and see if the error still happens. If it does not, some other addon might be responsible.

**Comment by johnnybgood89** [comment]
Ok thanks. I know that WDB isnt a problem, but now I deleted WTF and starting configuring addons again.

**Comment by Dyaxler** [comment]
For reference... line 1033 is: Questie:RedrawNotes() and is used quite often. Trust me, if it were that then you'd have every player complaining about it. EVERY player that uses Questie. :)

**Comment by johnnybgood89** [comment]
Ok thanks. Im mot familiar with coding so maybe Im replying too much but I just want to help when I can :D
