### ISSUE TITLE
Quest "Filling the Soul Gem" req 1 level

### ISSUE THREAD

**Issue by KasVital** [AeroScripts/QuestieDev#392]
http://db.vanillagaming.org/?quest=593
but before 
http://db.vanillagaming.org/?quest=592 
req 41 level

**Comment by Muehe** [comment]
So, I have been researching this. MinLevel 1 is actually the correct value DB wise, though it shouldn't be shown for this quest, as it can only be accepted when the parent quest (592) is active because it provides the required item for the parent as the reward. Child quests like this are marked as "Enabled by" on vanillagaming and twinhead.

Anyway, the MinLevel of the parent quest is way off, vanillagaming and [twinhead](https://vanilla-twinhead.twinstar.cz/?quest=592) have 41, [wowhead](http://www.wowhead.com/quest=592), cmangos and Questie have 30, and actually it should be 39 [if you know where to look](https://web.archive.org/web/20060416013418/http://wow.allakhazam.com/db/quest.html?wquest=592). Going to file a bug report at cmangos. Thanks for reporting!

As for Questie, we could remove required level of this child quest (maybe needs an additional nil check somewhere?). But the current DB is lacking data on child quest in general, so fixing all of them should probably wait till 4.0. We could also set MinLevel to the correct value of 39, or at least 41 for the parent quest.

**Comment by Muehe** [comment]
I have been informed this quest is part of a longer quest chain, of which the first quest has MinLevel 30. So the parent quest has the correct MinLevel in Questie. I'll wait for @Dyaxler to decide how we proceed on the child quest subject.

**Comment by Dyaxler** [comment]
If quests in the middle of a chain say min level 1 and the quest chain starter says anything but level 1 then they should be changed to match the quest chain starter at the minimum... Doesn't make much sense otherwise and could lead to confusion.

**Comment by Muehe** [comment]
We need new quest relation data before this can be fixed properly. Probably will not be in 3.7 release, but we are working on it.

**Comment by BreakBB** [comment]
The level requirements didn't change for Classic according to Wowhead. [This](https://classic.wowhead.com/quest=593/filling-the-soul-gem) still shows level 1 as required level.
