### ISSUE TITLE
Down the Scarlet Path

### ISSUE THREAD

**Issue by johnnybgood89** [AeroScripts/QuestieDev#398]
Down the Scarlet Path
 quest in desolace not showing any markers on map. 

http://db.vanillagaming.org/?quest=1052

**Comment by ZoeyZolotova** [comment]
Did you mean this quest? http://db.vanillagaming.org/?quest=261

**Comment by johnnybgood89** [comment]
Yes that one

**Comment by ZoeyZolotova** [comment]
I actually came across this earlier today myself. A bunch of "slain" objectives don't work because at some point in the past someone decided that rather than removing the word "slain" and searching for mobs using the remaining text (e.g. objective says "Undead Ravager slain", change to "Undead Ravager" and search for that mob), instead they added a whole lot of new mobs with the word "slain" appended. So now in the monsters database we have for example "Thistle Boar" and "Thistle Boar slain"... which is really ridiculous imo.

So the reason that Down the Scarlet Path isn't working is because in the monsters database we have "Undead Ravager" but not "Undead Ravager slain".

I'm in the process of fixing the underlying issue in my fork.

**Comment by johnnybgood89** [comment]
Nice to know that :)

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
