### ISSUE TITLE
Abandoning quest triggers 'stack overflow' error

### ISSUE THREAD

**Issue by Talyrius** [AeroScripts/QuestieDev#402]
Using the current master branch, I receive the following error when attempting to abandon a quest:
```lua
Interface\AddOns\!Questie\Modules\QuestieQuest.lua:672: stack overflow
```

The abandon quest prompt stays on the screen and selecting 'Yes' causes the error to recur. This happens for any quest. Disabling Questie restores functionality.

**Comment by Muehe** [comment]
I am unable to reproduce this issue. Have you raised your addon memory in the settings menu on the character selection screen?

**Comment by Talyrius** [comment]
Yes, it's set to 999 MB.

**Comment by Muehe** [comment]
Do you have tried running just Questie? I tried with only some dev addons activated and it worked flawlessly... From a guide I am writing on:

### Troubleshooting

To make sure no other addons interfere with Questie or the WoW API, try disabling all other addons and see if your problem is still reproducable.

Questie offers two commands that can be used for troubleshooting. The `/questie clearconfig` command resets Questie to the standard settings. The `/questie NUKE` command does the same, plus removing your characters finished quests from the SavedVariables. We recommend backing up your `WTF` directory before using them (see below).

There are also some basic steps that you can take for troubleshooting addons in World of Warcraft (the infamous *"Delete Cache, WDB and WTF"* Gamemaster reply). This also helps to ensure your problem is related to Questie.

1. **Deleting the Cache:** The WoW Client caches data it receives from the server into two different directories in its root path. This can lead to problems if the server is updated or switched, because your client and server have conflicting data. We recommend starting WoW using a batch file or shell script that deletes the `Cache` and `WDB` directories every time before starting the client, like explained [here](http://www.mmo-champion.com/threads/1339931-Start-WoW-amp-Delete-Cache-Combo). The client will create a new cache if none is present on startup. Note that the `Cache` directory is only created if the server actively pushes data for it, which many of todays servers don't.
2. **Reseting the configuration:** All settings in WoW get saved to the `WTF` directory. That includes addon settins as well as client settings, e.g. video and sound settings. To identify if your settings are causing a problem you can rename your directory to something like `WTF_Backup` and restart the game. A new `WTF` directory with standard settings will be automatically be created. If your problems persist, you can delete the new directory and

**Comment by Talyrius** [comment]
After some troubleshooting, I've discovered that it only happens in combination with [ShaguDB 8.0 Beta 1](https://github.com/shagu/shaguquest/releases/tag/8.0-beta.1). However, if you still require it, [here is a Gist](https://gist.github.com/Talyrius/c6d9edabea34574697e04dc3d2fdf93b) of my character's saved variables for Questie.

**Comment by Dyaxler** [comment]
Hmmm... Muehe we need to figure out what's triggering that bug. I'd like to keep Questie compatible with Shagu.

**Comment by Muehe** [comment]
That's why it is a beta. :smile:  Anyway, shagu asked me to port the repo, since he gets too many support requests for an addon he is not currently working on (seems he also deleted the issue tracker). I'll take care of this bug once I finished the port.

**Comment by Muehe** [comment]
@Talyrius Btw. I rechecked the beta download I provided, it included the icon graphics. Did you download the zip file containing a "r2" at the end? The first one I uploaded had indeed some data missing. If you had the first one, you can try this until I finish the port:

[ShaguDB-8.0-beta.1-enGB-complete.r2.zip](https://github.com/AeroScripts/QuestieDev/files/772890/ShaguDB-8.0-beta.1-enGB-complete.r2.zip)

**Comment by Talyrius** [comment]
I looked at my download history and it says I downloaded ShaguDB-8.0-beta.1-enGB-complete.r2.zip on February 7, 2017.

**Comment by Muehe** [comment]
Ok, then I'll have to reproduce and fix this later. Sorry.

**Comment by Dyaxler** [comment]
Re-wrote both quest abandonment functions. The issue was related to a recursive check to finish prior quests that shouldn't have been there in the first place.

**Comment by Dyaxler** [comment]
For context, Muehe encountered this error again after my fix and traced it to another source.

**Comment by Muehe** [comment]
A copy&paste error on my part, introduced here: https://github.com/Muehe/classicdb/commit/e9524bad9fa4c59d4515b65321ce72ed198bef70

@Talyrius You can try this instead of the ShaguDB beta:

[classicdb1.0-prerelease.zip](https://github.com/AeroScripts/QuestieDev/files/800948/classicdb1.0-prerelease.zip)
