### ISSUE TITLE
Hemet Nesingwary

### ISSUE THREAD

**Issue by do-you-even-curl** [AeroScripts/QuestieDev#405]
The quest [Hemet Nesingwary](http://db.vanillagaming.org/?quest=5762) has the wrong destination.
![hemet_nesingwary_wrong_location](https://cloud.githubusercontent.com/assets/24255259/22856897/333699ec-f09b-11e6-94e3-1d5380ffe759.jpg)

**Comment by Dyaxler** [comment]
I'm not even going to presume how THAT happened... 

We've made some significant changes to the DB already but we're at a point where its driving one of our Dev's NUTS... to say the least. A few have talked about attempting to pull a new DB from mangos core that will work with Questie v3. Otherwise, wait till v4 is released. :)

**Comment by ZoeyZolotova** [comment]
It might be trying to use the location of Hemet in Outland. I'll see if it happens for me.

**Comment by ZoeyZolotova** [comment]
Sorry for the delayed response. Yes the issue was that it was trying to locate "Hemet Nesingwary" whose location is listed as in Outland. It will be fixed as part of the next version.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
