### ISSUE TITLE
Reoccurring issue with latest version of questie

### ISSUE THREAD

**Issue by isebashin** [AeroScripts/QuestieDev#407]
![2017-02-14](https://cloud.githubusercontent.com/assets/25778238/22946415/f72f3354-f2bc-11e6-9f35-17189cd43475.png)

**Comment by Dyaxler** [comment]
There was a recent post on twitter from the Elysium support folks about the latest server maintenance advising everyone to delete their WDB folder. Did you do that?

Does this happen when you login? Reload your UI? Turn in a quest? Fart? Sneeze? Details man! :)

**Comment by isebashin** [comment]
@Dyaxler I deleted my WBD folder and still no luck :( .This only happens when i first log in to any character There are 2 error messages i get and i will link them in the post. This is when i login and it doesn't go away iv'e tried all the commands and still no luck.
![2017-02-15 1](https://cloud.githubusercontent.com/assets/25778238/22968665/f6a0e8d2-f330-11e6-9c5c-9e4f66d32795.png)
![2017-02-15](https://cloud.githubusercontent.com/assets/25778238/22968677/00b15334-f331-11e6-8132-98ffd1448d0f.png)

**Comment by ZoeyZolotova** [comment]
What other addons do you have enabled?

**Comment by isebashin** [comment]
@ZoeyZolotova no other addons

**Comment by Dyaxler** [comment]
The error is occurring because it can't find the Astrolabe namespace or it can't find Astrolabe.lua. Line 605 in Questie.lua is ```Astrolabe:isMinimapInCity()``` and it's in the VARIABLES_LOADED event which happens shortly before the player enters the world.

There has got to be something wrong with your client or you've installed Questie wrong. :( Or something else is interfering.

Can you make a backup copy of your WTF folder and then delete it. Let's rule out Saved Variable corruption.

**Comment by Muehe** [comment]
The function might be called too soon when using this event:

> Fires when non-addon-specific saved variables are loaded. Addons should generally use ADDON_LOADED to determine whether their saved variables have loaded.

http://wowprogramming.com/docs/events/VARIABLES_LOADED

**Comment by isebashin** [comment]
@Dyaxler Is there a version i should install or anything? i deleted my copy of my WTF file and no luck :(

**Comment by Muehe** [comment]
@isebashin Current release is v3.69. You can always find the most up-to-date version here: https://github.com/AeroScripts/QuestieDev/releases

**Comment by Dyaxler** [comment]
```Astrolabe:isMinimapInCity()``` doesn't save anything to the users Saved Variables but if his WTF is corrupted it can prevent other functions from firing. I only zero'd in on the Astrolabe function since it is the one that triggered the error and it's a core dependency for Questie.

The first error is saying that it can't Index this function: Astrolabe:isMinimapInCity()... the name space 'Astrolabe' is nil. The second error is basically the same... can't find the name space 'Astrolabe'.

I noticed that the 'A' in the astrolabe directory in Questie is lowercase but all references to it are in Uppercase. I don't think case sensitivity matters but maybe in your case it does isebashin? What OS are you running? And to confirm... you are running an English client?

**Comment by isebashin** [comment]
@Dyaxler im running windowns 10 and i am running the English client

**Comment by ZoeyZolotova** [comment]
I can only think of a few general things you can do to try to determine the cause. First try deleting the !Questie folder and recopying a fresh version from the latest download link. If that doesn't work try going back a commit at a time and repeating the process until you have a version that works, and then let us know which commit that was.

Sorry if that doesn't help.

**Comment by isebashin** [comment]
@ZoeyZolotova i ran a repair of my hdd and installed a new version and now it works, thanks guys :)

**Comment by Dyaxler** [comment]
I had a sneaky suspicion that this was going to lead to file corruption of some kind. :( Sorry you had to go through such drastic measures. But... now you won't have any issues with other mods you decide to use.
