### ISSUE TITLE
Questie still abandoning the wrong quest at times

### ISSUE THREAD

**Issue by fildew** [AeroScripts/QuestieDev#415]
Was gonna abandon a quest today and got this:

https://cloud.githubusercontent.com/assets/20835970/23765573/ecd51a98-0501-11e7-97e1-c75a5d96eddf.png

Restarting the WoW client fixed the issue, so there seems to be some event triggering this ingame.

Edit: Running Questie 3.69.

**Comment by Lebaowski** [comment]
I run across this problem constantly if my questlog is full while trying to disband a quest. Some quests will disband, while others keep showing the wrong quest at the confirmation box after clicking 'Abandon'.

For me it seems to have to do with the combination of EQL and Questie though, if i disable either one and leave the other running, the questlog will disband just fine.

**Comment by Dyaxler** [comment]
We found and fixed the issue during development for v3.70. We had to use a very old work around in functions that selects specific quests in the log. The old issue is that these functions would leave the quest selected without clearing it causing the next function to have the wrong quest selected. In the current dev build, this issue no longer happens.

I'm sure some of the more savvy users of GitHub has found it but we're dumping our dev commits here:
[Version3.70 (DEV-BUILD)](https://github.com/Dyaxler/QuestieDev/tree/Version3.70)

Use with caution but it's almost ready to be released as a "Pre-release build". Ton's of issues have been fixed and most of the code has been re-written.

**Comment by fildew** [comment]
You are the best, I'm waiting anxiously for the pre-release!

**Comment by staplerx300** [comment]
noice

**Comment by ZoeyZolotova** [comment]
I'd like to clarify the issue here. Vanilla wow addons can only read the objectives of the currently selected quest. So in order to read the objectives of each quest, the addon has to select each quest one at a time and read the objectives. Some addons (like Questie v3.69) forget to reselect the previously selected quest after finishing reading through the quest log. 

If you close and reopen the quest log, and a different quest is selected, then you know the bug has occurred. Here's a demonstration using the addon QuestItem. 

![abandonbug](https://cloud.githubusercontent.com/assets/22694317/24070910/468fb786-0c1a-11e7-87ec-5a0f35fa0acb.gif)

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).
