### ISSUE TITLE
Tracker does not add quests

### ISSUE THREAD

**Issue by lordhelmchench** [AeroScripts/QuestieDev#434]
On one account the questlog does not update my quests in the tracker anymore.
One Quest is visible in Questie Tracker, even when the quest is not marked anymore.

All other quests are not shown. 

My Questie-Data from \Zeth'Kur\name\SavedVariables
[!Questie_.lua.txt](https://github.com/AeroScripts/QuestieDev/files/1032955/Questie_.lua.txt)

In the file there are other quests under QuestieTrackedQuests than I have chosen.

Default-Tracker:
![wowscrnshot_052617_225339](https://cloud.githubusercontent.com/assets/17217403/26512297/395d267a-4266-11e7-84e4-ea583a23d120.jpg)

Questie-Tracker
![wowscrnshot_052617_225244](https://cloud.githubusercontent.com/assets/17217403/26512312/442104e6-4266-11e7-9987-a189f5ae44cc.jpg)

**Comment by lordhelmchench** [comment]
Nuking DB worked when giving up quest and take the quest anew.

**Comment by Muehe** [comment]
This issue will probably be fixed in the next release, as Dyaxler reworked the whole tracker for v3.7.

If you want your finished quests back after the nuking, you should be able to copy the content of the `QuestieSeenQuests` table in the file you uploaded here to the table in the new automatically created file (make sure client is not running while you do).

Closing this issue, as it seems to be resolved. Please reopen or create a new issue if you keep having problems. Thanks.

**Comment by lordhelmchench** [comment]
Thanks a lot
It worked. After I copied back the SeenQueests everything was working again.

Thanks a lot for you suport and the great tool!

2017-05-26 23:56 GMT+02:00 Muehe <notifications@github.com>:
