### ISSUE TITLE
Restore database to questie

### ISSUE THREAD

**Issue by woopydalan** [AeroScripts/QuestieDev#437]
Hello, 

My game reset settings back to default unexpectedly, and now all the quests I have finished are back on the map for questie. I'm wondering if there's a way for questie to search the database again and extract already completed quests. It happened for other addons too (lost all gatherer nodes on map). I know the addon for retail wow questcompletionist allows you to do a query on the database to update itself, it would be great if questie could do this as well.

Edit: I did /questie NUKE, I hope this didn't ruin it

Thanks

**Comment by Muehe** [comment]
The NUKE command removes all finished quests from Questies internal DB. This means you might see quests as available which you already finished and some quests with a prerequisite might not show.

You can not recover the internal DB if you used the NUKE command, but your issue sounds like you might have changed the server, the server got renamed, or you accidentally deleted the WTF directory, which holds game settings and SavedVariables for addons. You can poke around in there and see if you find a `!Questie.lua` in the SavedVariables directory belonging to the affected character which has entries in the table `QuestieSeenQuests`.

**Comment by woopydalan** [comment]
Yes, I did delete the WTF directory after my game unexpectedly reset.

 Is there any plan to introduce a feature in questie to allow it to query the server's db and extract information regarding quests completion, rather than having to rely on an internal DB? I did the NUKE command as well so all hope is lost I guess. A query seems better in case someone was to remove the addon, or start playing without the addon and later getting it.

**Comment by Muehe** [comment]
Sadly the commands to do that were introduced in WotLK, so that won't be a possibility in Vanilla and TBC. Questie does however mark quest as finished recursively, so if you finish part 7 of a quest line, parts 1-6 are marked as finished as well. You can also mark quests as finished by shift-clicking the exclamation mark on the map, but most low level quests should be hidden by the level filters anyway.

And yes, with your WTF directory deleted the database is completely gone, unless there is still a copy of it in the trash or you are crazy enough to use a recovery tool and the sectors haven't been overwritten with other data yet.
