### ISSUE TITLE
Questie shows Rexxar in Ruins of Alterac instead of Desolace

### ISSUE THREAD

**Issue by Ghamarro** [AeroScripts/QuestieDev#441]
Every quest that has you talk to Rexxar, questie shows the question mark on the map to be in the Ruins of Alterac, where Rexxar of course most certainly is not, as he is in Desolace.

**Comment by Muehe** [comment]
Same as with #445, will have to look into this at a later date. Thanks for the report though.

**Comment by Muehe** [comment]
I tested this in v3.7.0 and Rexxar was shown in Shadowprey Village instead of Alterac. This is still wrong because that's where his replacement was put in TBC, so I added a few locations along his path:


![screenshot_2017-10-07_08-00-08](https://user-images.githubusercontent.com/8838573/31305275-35d4bdae-ab36-11e7-9776-1719458d62b6.png)

![screenshot_2017-10-07_08-00-39](https://user-images.githubusercontent.com/8838573/31305278-39071382-ab36-11e7-8408-f85a247eb87e.png)
