### ISSUE TITLE
Druid Horde Bear Quest wrong marker

### ISSUE THREAD

**Issue by Alexxino7** [AeroScripts/QuestieDev#445]
The part of the quest chain named "Body and Hearth" where you have to face Lunaclaw for your bear at form has the wrong marker on the map.

The marker is set Darkshore but the actual quest objective is between Barrens and Mulgore as per quest log.

**Comment by Muehe** [comment]
Thanks for the report, I'll try to look into this if ever get around to fixing that blocking bug on the development branch.

**Comment by Muehe** [comment]
I have looked further into this. Right now both of the locations, the one in Darkshore and the other in the Barrens are shown. This is due to the objective text the quests use, which is exactly the same. There is no easy fix for this in the way Questie currently works, so this issue might stay open for a longer time.

Fun fact: When you get the Horde quest, you can use the Lunardust on the stone in Darkshore, but Lunaclaw will spawn in the Barrens :laughing:

**Comment by ZoeyZolotova** [comment]
Looking through the questie events with more than one location, it seems to me that this issue only occurs for that one druid quest. Do you think it's fine to fix it in the following hard-coded manner?

When getting even locations: if event name is lunarclaw event, then if player race is Tauren use location 1, else use location 2. otherwise use regular event logic.

A less hard-coded way may be to add required race information to the affected event location. i.e. the 5th parameter can be 77 or 178 (or 8 and 32 for just nightelf and tauren) and then the event logic can check requirements if there's a 5th parameter in the location.

Now that I think about it, the 2nd way I mentioned is probably better, because it'd open up the ability to show only relevant locations for holiday/pvp quests that apply to both factions. E.g. quests 7122 and 7124 (Capture a Mine) show both horde and alliance entrances to Alterac Valley.

**Comment by Dyaxler** [comment]
I like option 2 as well...

**Comment by ZoeyZolotova** [comment]
Oops I got confused with the race binary stuff.
