### ISSUE TITLE
O_o Databases...

### ISSUE THREAD

**Issue by Lichery** [AeroScripts/QuestieDev#448]
OMG... what is this nonsense? how did you make the database that they are in this form? 
all languages are mixed, lots of data are missing, a lot of data from the BC and WOTLK... O_o

File monsters.lua:
Chinese
![bandicam 2017-09-10 02-10-34-048](https://user-images.githubusercontent.com/24303693/30244770-5760e80e-95cd-11e7-996c-9e05f34a33b7.jpg)
Korean
![bandicam 2017-09-10 02-14-44-479](https://user-images.githubusercontent.com/24303693/30244794-d66c4dbe-95cd-11e7-9ff7-55654c258615.jpg)
French
![bandicam 2017-09-10 02-15-20-625](https://user-images.githubusercontent.com/24303693/30244798-e9c568d2-95cd-11e7-894a-b6ef182245b1.jpg)

File items.lua:
Deutsch
![bandicam 2017-09-10 02-17-55-391](https://user-images.githubusercontent.com/24303693/30244808-5f4ee4de-95ce-11e7-98ae-9751acc9022e.jpg)

File finishers.lua:
Russian
![bandicam 2017-09-10 02-26-59-539](https://user-images.githubusercontent.com/24303693/30244845-962208d2-95cf-11e7-82f3-ee6d4ac0b742.jpg)

File zone.lua:
a lot of mistakes...
![bandicam 2017-09-10 02-20-00-240](https://user-images.githubusercontent.com/24303693/30244817-b9ea351a-95ce-11e7-9ee2-a26d25fe5f85.jpg)

P.S. I apologize for the expression, but it's not a databases, it's shit!

**Comment by crumdidlyumshis** [comment]
This is a really great way to get developers to help you out! You are the fuck heads that make us cry inside. Could you elaborate on this in a more meaningful manner rather than blasphemy?

**Comment by Muehe** [comment]
The DB is the way it is because the addon was forked from QuestHelper (a TBC addon), and then was developed by different devs over time.

Also it works™.

A redo of the DB was planned, but since development of v3.7 got stalled due to the two main devs of it disappearing, I had to postpone the redo.

Feel free to provide a Pull Request though, just note that our current dev branch is not found on this repo, but [here instead](https://github.com/Dyaxler/QuestieDev/tree/Version3.70) (still looking for feedback on my last commit btw.).

Since this isn't really a bug report or feature request, I'm going to close it. Feel free to continue this thread if you have any other questions (or join our Discord channel: http://discord.gg/phKnHVu).

**Comment by Lichery** [comment]
If necessary, I can provide the correct data for the quests from the mango classics, but without the structure. Ie just text, without numeric data. Thus, you will have data only on the classic, without unnecessary data from other patches.

When I saw in what state of the database, I felt bad. The addon is very good, but the state of the databases spoils the impression of it. I really hope that databases will be redone.

**Comment by Schaka** [comment]
Database was redone years ago. If you check out the Questie2 branch, there were a lot attempts at making Questie much much better. We took data from cMaNGOS ages ago.

That being said, before any of the bigger features were tested thoroughly enough to be pushed into production, all of the originals devs got bored of vanilla and burned out. Even the devs that took over got burned out over time. The database isn't the problem, rewriting all the logic around it is.
