### ISSUE TITLE
SelectQuestLogEntry(index) Error

### ISSUE THREAD

**Issue by Marvin732** [AeroScripts/QuestieDev#453]
Hi !
I get the Error code, Interface\AddOns\!Questie\Modules\QuestieNotes.lua:276: Usage: SelectQuestLogEntry(index) on the Mob "Young Forest Bear" while i already ended the quest and when i hold my mouse on the mob, that error pops up, same as at the quest for the Potion for the Young Lovers but i dont know the errorcode anymore since its gone after relogging :/

**Comment by Muehe** [comment]
Sounds like you might be using an outdated version, as that line calls a wrapper function `QSelect_QuestLogEntry()` instead of the one in your error message in the current release.

The current stable release is 3.69 and is found here: https://github.com/AeroScripts/QuestieDev/releases 

The development version can be downloaded from https://github.com/Dyaxler/QuestieDev/archive/Version3.70.zip.

**Comment by Muehe** [comment]
I have encountered a similar bug, so this might actually be a problem. I will look into this further when I have the time. It might be worth noting that I tried to reproduce the error on the 3.7.0 version and could not do it so far.

**Comment by Muehe** [comment]
New beta release is out. It can be downloaded [here](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.0-beta).

**Comment by Dyaxler** [comment]
Yeah this was a map note bug that Zoey fixed. This shouldn't happen in the Beta Version.

**Comment by Muehe** [comment]
Thanks for the info :+1: 

Assumed solved. @Mar If you continue having problems, please re-open the issue or create a new one.
