### ISSUE TITLE
Questtracker "blinks" in the middle of the screen sometimes, probably on update

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#456]
Questtracker "blinks" in the middle of the screen sometimes, probably on update

Should probably have the tracker hidden until it is moved to it's correct place.

**Comment by Eulogies** [comment]
I have this issue as well. Causing quick pauses in game.

**Comment by AriinPHD** [comment]
I too experience this strange issue. Just pitching in as a "vote" for prioritization. :)

(Although I cannot confirm this is due to !Questie, but since the Beta version I'm also noticing that the mouse cursor gets moved around when the quest tracker "blinks". This can sometimes cause me to turn my character around in random directions (i.e. 180 degrees) while I use the mouse button 2 (right) to move and look around).

**Comment by trav75** [comment]
I am having this issue as well.  I am pretty sure the default quest tracker is flickering.  Mine was flickering in the middle of the screen as well and I could see that it was the default quest tracker.  So I turned off the QuestieTracker, and I then moved the default tracker to the side of the screen.  After that I enabled the QuestieTracker again.  Now the flickering is on the side of the screen where I moved the default quest tracker.
