### ISSUE TITLE
Quest with wrong min level

### ISSUE THREAD

**Issue by obidobi** [AeroScripts/QuestieDev#464]
Quest: Errand for Apothecary Zinge
Current Min Level: 38
Correct Min Level: 42

**Comment by Muehe** [comment]
I have checked both quests with these names (232, 238) in the CMaNGOS classic-db and they both had MinLevel 38 (which makes sense, since they are part of a longer chain).

There are two possible explanations for these quests having a different MinLevel on other servers:

1. The server uses data from people that didn't accept this quest before level 42.
2. The server is using a patch version < 1.12.1.

The CMaNGOS data could be wrong too[1], but until I see a source for that I will leave it at 38, since setting the MinLevel to 42 would lead to people that could already accept this quest missing it, because they are on the "wrong" server.

[1]: I checked the Kronos database too, and they have MinLevel 42 for both quests, but then MinLevel 38 and 40 for the next two quests in the chain, which seems wrong to me.
