### ISSUE TITLE
Quest item chance drop [suggestion]

### ISSUE THREAD

**Issue by EvgenStudent** [AeroScripts/QuestieDev#472]
If you can add chance drop for quest items, it will be great.
For example it can be shown up on the mob tooltip.

**Comment by Dyaxler** [comment]
This might be best to add this to the new database. The drop %'s would have to come from there.

**Comment by BreakBB** [comment]
[The scraper](https://github.com/BreakBB/wowhead_scraper) could get all items dropped by an NPC and add it to some separate file.

**Comment by Gogo1951** [comment]
@EvgenStudent ,

While I like the idea, we'd almost certainly have to pull from WoWHead to get data... and their drop rates for quest items are notoriously off. They haven't done a great job of filtering patches when data was collected, or when someone was on a quest or not before looting -- so a lot of items that are fairly common on quests show up as like 1% drops.

Is this needed? If not, can we close it up? Thanks!

**Comment by BreakBB** [comment]
This issue is being closed because the level of development effort required is substantial and doesn't line up with the number of requests we've received from current users. The issue will remain as an archived issue on GitHub, and should you ever want to do the development work you can reopen it and submit a pull request with your work. Sorry your idea didn't make the cut this time around, but please keep the suggestions coming and thanks for taking an interest in improving Questie!
