### ISSUE TITLE
Crash in the 2° mission Horde(orc,troll)

### ISSUE THREAD

**Issue by Nyxot** [AeroScripts/QuestieDev#475]
I use the v3.7 and when you try to finish the second mission the addon crash and cant finish the mission.
said something like "addon/questie/.../.../.../ try write numval: null"

**Comment by Muehe** [comment]
I have just tested all quests in the Valley of Trials and none of them bugged out on me. It's possible this quest has been fixed since the beta release, please download the [master branch](https://github.com/AeroScripts/QuestieDev/archive/master.zip) (copy only the `!Questie` folder out of the zip archive) and retest this. If it happens again, please screenshot the error message.

**Comment by Dyaxler** [comment]
We should go ahead and push a new version to make it easier for folks to install it. :)

**Comment by Muehe** [comment]
Yeah we should, but I wanted to let the latest changes sink in for a few days. Some people use the method described in [this thread](https://forum.lightshope.org/viewtopic.php?f=34&t=310) to update to the latest commit, so I am kind of abusing them as beta testers. :laughing: The current state seems to work fine though, as none of these "bleeding-edge" users complained yet. Gonna prepare a proper release over the next days.
