### ISSUE TITLE
questing error 107 arethmical value (nul) 

### ISSUE THREAD

**Issue by bolshoy705** [AeroScripts/QuestieDev#476]
First happened while picking a quest at desolace dont know which one tho but there's an error 
had to disable addon

**Comment by Muehe** [comment]
Thanks for the report, but sadly this is not enough information to investigate this issue.

The error message would have mentioned a file name and a variable name, which are needed to know where the error occured (107 is the line number).

Which version of Questie you are using, or if you are using the current state of the master branch the download date, would also be useful information.

I'll try to look into this but without this information it could take some time (although I have a feeling that it's related to the problem discussed here: https://github.com/AeroScripts/QuestieDev/commit/0508aaa473d1c1bbb873bec3b63fdfa37878f376 ).

**Comment by bolshoy705** [comment]
Seems that it happens every time i pick or turn a quest it says : 
Interface/Addons/Questie/QuestieTracker.lu a: 107 attempt to perform on local 'have' (a nil value)
I disabled it for like 5 hours cause i thought it was because of a certain quest
Same error when i turn the quest Stealing Supplies and getting the quest Ongeku from Uthek the Wise at desolace

**Comment by Muehe** [comment]
Thanks for the info.

Assuming you are using the current state of the repo, as that is the only version where arithmetic is used in that particular line. Gonna see what I can do about this.

**Comment by Muehe** [comment]
First find: the command is only executed when the "tracker list direction" option of Questie is enabled. Disabling it might fix this.

**Comment by ZoeyZolotova** [comment]
Looks to me like it's not the most recent version. The variable 'have' appears on lines 150 and 164.

**Comment by Muehe** [comment]
Oh yeah, didn't see that. There it is checked for being nil, so if there was a bug in an old version it's probably fixed. @bolshoy705 Please check your version number.

**Comment by bolshoy705** [comment]
version 2.0.4

**Comment by Muehe** [comment]
Oh yeah, that's quite old and updating it is not really trivial if you want to keep your list of finished quests. Just a sec I wrote instructions on updating down somewhere.

**Comment by Muehe** [comment]
Ok, download a new version of Questie (think the best would be to download the [master branch](https://github.com/AeroScripts/QuestieDev/archive/master.zip) here from Github) and then:

1. Create backup of the `WTF` folder.
2. Delete the old Questie version (folder named `Questie`) from the `Interface/Addons` folder.
3. Copy the new Questie version (folder named `!Questie`) into the `Interface/Addons` folder.
4. Start the game, login to each character once, and close the game (the purpose of this is to create new files in the `WTF` folder and prevent a certain bug which might occur when updating from version 3.96 to 3.7).
5. For each character, go to `WTF/Account/<ACCOUNT_NAME>/<SERVER_NAME>/<CHARACTER_NAME>/SavedVariables/`, open the file `Questie.lua` with a text editor (do not confuse it with the file in the same directory `Questie.lua.bak`), copy the complete table called `QuestieSeenQuests` and replace the one in the `!Questie.lua` file with it.

My plan was to write a bash script for the last part before release, because it can be confusing and certainly tedious. But this method is reported to have worked for the same version 2.x to 3.x update before.
