### ISSUE TITLE
Not tracking Kill/Pickup quests correctly on the Map / Objective(ie turnin)

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#48]
Map and turnin progression is not updating correctly,

![example](https://cloud.githubusercontent.com/assets/8261057/7107676/01c8024a-e16d-11e4-8af5-d8257aa50dda.PNG)

**Comment by AeroScripts** [comment]
It's possible this is another "zombie notes" issue, see #14. I was assuming this was fixed, but apparently not. 

Since we are maintaining our own version of cartographer now, it might be easily fixed by adding a validation check in cartographer that asks questie if the points are still valid. Ideally questie should be removing them, but it seems there's always one reason or another for it to "forget" that a note exists.

**Comment by Schaka** [comment]
I think the issue is just that with the current system, it doesn't re-draw all notes on QUEST_LOG_UPDATE, thus if he logs in with 1/2 Haldarr Trickster Slain, that's what's being shown in the notes tooltip. But because notes don't update.

If we move to Astrolabe, you parse it a "frame that it places on the map (I think!) so we could anchor a tooltip to each frame that shows OnMouseOver or something. So we could just maintain a tooltip that would request new information OnShow.

**Comment by Logonz** [comment]
The thing is that While the questlog acually shows the quest as complete it does not update it with the turnin, so it's a twofold problem i would guess BECAUSE the notes are not updated and removed it does not ADD the questionmark on the map either.

**Comment by Schaka** [comment]
Oh no, that actually is a real problem then. Even upon opening your quest log, it does NOT recognize the quest as complete? That seems very broken. Sometimes, it's just that QUEST_LOG_UPDATE is not fired properly by the server, so the log/trackerframe don't update properly.

But opening your questlog should fix that, except sometimes it doesn't - apparently.

**Comment by Logonz** [comment]
Noticed a pattern. It seems like the last event update is lost in some way,
The quest "The corruption of the jadefire" has 3 objectices, kill 11,9,9,1
On the last part of ALL the objectives (ex, 11 is done, the 11th kill is not recorded) it does not update accordingly, this happened 3 times on the same quest.
![example2](https://cloud.githubusercontent.com/assets/8261057/7117402/b3677c66-e1f8-11e4-9c1b-91a382d7214f.PNG)

**Comment by Schaka** [comment]
Actually, our log function already has a debug level. It's Questie.debugLevel. We just keep most stuff commented out because we only need debug prints for new features (most of the time anyway). 
You're right though, we should keep everything in and just set the debug level for it super high. The idea was to allow the user to switch debug mode on and off once we implement the menu.

There's also QuestieDebug (in your SavedVariables) which keeps some information. We just haven't gotten around to making a tutorial on how to submit information. It's mostly for broken quests and objectives.

**Comment by Logonz** [comment]
Had the problem again now, but this time in a very early part of a quest,
1/12 was not logged, as soon as i get 2/12 it logged both, so i would guess the problem is that the event just isn't triggered, no idea how you would fix that.

**Comment by AeroScripts** [comment]
Could implement a temporary fix by having it recheck all quests every ~10 seconds or something, if it is the events not firing properly.

And yeah we do have a log function, but a lot of things don't actually have calls to it. I'll go through and add debugging everywhere in a little bit.

**Comment by Logonz** [comment]
Do that, and if it gets laggy do some kind of updatequeue system, go through one of the quests in the qlog every 0.5 second or something, (20 quests in 10secs)

**Comment by Sparh4wk** [comment]
Yep can confirm Logonz words about this issue.. Im using questie from yesterday, but this bug is definately there.. now Im doning Quest Foul Magics.. I looted one Amulet, but map and quest tracker tells me other wise... screenshot attached. you can see the Amulet as NEW in my inventory..

![5faxjrf](https://cloud.githubusercontent.com/assets/7014826/7131577/31dec26a-e281-11e4-912a-eaffd5e3cac8.jpg)

**Comment by Logonz** [comment]
I think i found the bug.

in
function Questie:QUEST_LOG_UPDATE()

´´´´LUA
 for r=1,count do
                    local desc, typ, done = GetQuestLogLeaderBoard(r);
                    
                    
                    if not done then -- This is where it bugs, i does not update the objective because it says the objective is done.
                        questComplete = false;
                        if selected then
                            --DEFAULT_CHAT_FRAME:AddMessage("SELECTED " .. q, 0.95, 0.1, 0.95);
                        else
                            --DEFAULT_CHAT_FRAME:AddMessage("NOTSELECTEd " .. q .. " " .. in, 0.95, 0.1, 0.95);
                        end
                        this:processObjective(q, desc, typ, selected, mapid, r)
                    end
                    ---DEFAULT_CHAT_FRAME:AddMessage(typ, 0.95, 0.95, 0.5);
                    ---DEFAULT_CHAT_FRAME:AddMessage(done, 0.95, 0.95, 0.5);
                    
                end
´´´´

Look into this, you guys have a much better knowledge of the codebase than me.

**Comment by Logonz** [comment]
Did a fork fix
https://github.com/Logonz/QuestieDev/commit/d5720e08a66d0f9f1d84166c0795307b745844ba

Not 100% tested when this is posted but it seems to be working

**Comment by AeroScripts** [comment]
Wow thanks for your contribution :D, I'll do a little testing then I'll pull in your request.

**Comment by Sparh4wk** [comment]
well I dont know if this is a bug, but it doesnt count first quest item to tracker or map + I tryed your version.. but no luck at all.. its the same :( It even gives me string error when I want to see quest rewards in quest log.. I even tryed remove EQL3, but its the same.. screenshots attached +1 dunno why I cant track some quests.
![q8oew0s](https://cloud.githubusercontent.com/assets/7014826/7174704/4285b060-e40c-11e4-9cc6-113a009dfc3e.jpg)
![84n9xw5](https://cloud.githubusercontent.com/assets/7014826/7174702/428421a0-e40c-11e4-8bcd-9b13d435fad2.png)
![pxekr46](https://cloud.githubusercontent.com/assets/7014826/7174705/428646ba-e40c-11e4-802c-4d6f7f7638b3.jpg)
![19wldmg](https://cloud.githubusercontent.com/assets/7014826/7174703/4284c452-e40c-11e4-8df2-2062793f3e85.jpg)

**Comment by Schaka** [comment]
Took the liberty to merge your changes into our master after reviewing them briefly. Thank you for the fix.

**Comment by Sparh4wk** [comment]
I deleted all my addons and wtf etc.. downloaded questie with logonz commit, but still as you can see even after quest is complete, there is still note on the map and even 0/3..

![zmi4drk](https://cloud.githubusercontent.com/assets/7014826/7177029/dcaf8924-e423-11e4-94dd-d446d8ecb7fe.jpg)

**Comment by Schaka** [comment]
The quest you've tested it with is already done, right? Logonz commit checks if a quest is entirely done, and if it is doesn't add anything to the notes. Aero and I are both inconvenienced right now, but we'll take care of it later.

Logonz, if you want to participate in the project on GitHub as a collaborator, you can tell us and Aero will add you to the project.

**Comment by Logonz** [comment]
About the error on quest items, I've had the same problem, some quests seem to throw errors, was this only on one quest or all in your questlog?

And the problem in that case is that the note is not removed correctly when the quest is done it is supposed to not update the notes when it's done so the 0/3 is expected if no update is tiggered within you getting the first item and the last. But the ticks should be faster than 3 pulsing blue shards so it's still a strange bug.

Im leveling 57, 60 today so i will run tests and fix any potential bugs i encounter with my fix (did the fix at 3 am didn't expect such a fast merge! :+1: )

Schaka, It would be really fun to be a collaborator!

**Comment by Sparh4wk** [comment]
Logonz: 

only few quests have this error..
and dunno why notes doesnt update sometimes with objectives.. same with first quest items doesnt count on note or to tracker

**Comment by AeroScripts** [comment]
Just made you a collaborator Logonz, welcome to the team :D

**Comment by Logonz** [comment]
Sparh4wk now that im more of an offical capacity i'll see if i can look into it! :+1: 

Thanks! Looking forward to being on the team!

**Comment by Schaka** [comment]
Shoot either of us a PM on the Nostalrius forums and we'll invite you to our Skype conversation.

**Comment by Logonz** [comment]
Sent to Scamp!

**Comment by Logonz** [comment]
Closing this because it works for now, and a new system handling notes is coming.
