### ISSUE TITLE
a nil value

### ISSUE THREAD

**Issue by Meridaw** [AeroScripts/QuestieDev#481]
![questie](https://user-images.githubusercontent.com/26133646/34469565-360fe76e-ef22-11e7-994d-52513c42874b.png)

Got this just after delivering the quest.

**Comment by Dyaxler** [comment]
I'm assuming that is line 225 in QuestieTracker.lua? If so this is occurring in the QuestieTracker:createOrGetTrackingButton(index) function which doesn't get called while a quest is being completed. 

Looking over lines 222 - 225 in the current build:

> 
>         btn:SetScript("OnEnter", function()
>             local questHash = btn.hash;
>             local quest = QuestieCachedQuests[questHash];
>             local questTitle = quest["questName"];

...based completely on the error, and a little logic, it's not setting the "quest" variable: 

> local quest = QuestieCachedQuests[questHash];

This (lines 222 --> 225 and below it) little chunk of code displays a tool-tip when you hover over the tracker... now this error could be occur'ing when it was trying to build the tool-tip just after or during the quest was completed. If it was just a "one off" I'd just call it bad timing. But if it keeps happening over and over again or if you figure out a consistent bug reproduction steps, please let us know. Otherwise, we'll have to build in some kind of nil check if it becomes a huge problem. So far I haven't encountered this issue.

Are you running the latest release?

**Comment by Meridaw** [comment]
Yes, im running latest release with the install instruction. This is the first time i got it, not a problem at all.

**Comment by Meridaw** [comment]
I had a server rollback, so i had to do over the quest. This time i did not get the error, and the quest tracker was not active when i completed the quest.

**Comment by Dyaxler** [comment]
Given the fact that it's tool-tip code that makes perfect sense. Please let us know if it happens again. Thanks for the bug report! /cheers
