### ISSUE TITLE
Profession quests should only be shown if the player has the required profession

### ISSUE THREAD

**Issue by Hiethen** [AeroScripts/QuestieDev#488]
http://db.vanillagaming.org/?quest=6607

**Comment by Muehe** [comment]
This quest is working fine, but to see it you have to enable the `Show Profession Quests` option.

Note that we do not support showing quests based on the actual skill requirement yet, which is why this option exists. We have the needed information in our DB but it is not used by the code other than for simply switching the profession notes on/off.

We lack code for mapping the skill IDs saved in the DB to the profession names and for checking if the player has the profession and the necessary level.

**Comment by Hiethen** [comment]
Thanks for the reply, I forgot about that option.

**Comment by Muehe** [comment]
Feature added as of commit 0d36468d219327331571a39d3e506502e189f568
