### ISSUE TITLE
LUA Error broke !Questie

### ISSUE THREAD

**Issue by shadowrich7** [AeroScripts/QuestieDev#496]
My questie was working perfectly then came my LUA error. Questie is not showing anything on my map or minimap. Error message is in my chat window. I've tried a clean !questie install, deleting WTF, and using a friends QuestieQuest.lua folder. None of my attempts were successful. Anyone have any ideas?

https://imgur.com/a/34cy1

interface/addons/!questie/modules/questiequest.lua:1071: attempt to index field '?' (a nil value)

**Comment by Killval** [comment]
Hey yo shadowrich, I found a fix to this!!!! remove the quest for Watcher Callahan <The Night Watch> in duskwood, and then activate questie again and reload, for some reason the moment i accepted this quest it bugged out with same error code as u. Let me know how it works for you!

**Comment by shadowrich7** [comment]
That worked! Thank you so much for the suggestion

**Comment by Muehe** [comment]
So that's why. We removed that quest following issue #411 because it doesn't exist in 1.12.1 anymore. Likely you guys are playing on a server with a (core) version < 1.12. This quest will not be added back to the DB, since Questie is explicitly a 1.12.1 addon.

Anyway, Questie shouldn't crash if it is missing a quest so we are going to fix that soon™.

**Comment by Killval** [comment]
hey thanks yeah I heard thru chatting with some one that it was apparently a quest added in wrath of the lich king, I have no idea what it is doing on Kronos 3 vanilla WoW server then. Either way I'm glad it was just a simple fix. I'm happy to help shadow!

**Comment by thevipe** [comment]
ahhh i had the same problem with that q  deleting my issue i setup

**Comment by rafis** [comment]
"Questie shouldn't crash if it is missing a quest so we are going to fix that soon™." fix please.

**Comment by Muehe** [comment]
This issue was due to me not removing everything in the database related to the Watcher Callahan quest in issue #411. Removed everything now and added a check to make sure issues like this get printed to the debug channel instead of crashing Questie.

This means that when people accept this quest now, Questie will just show nothing about it. Also, if some other idiot like me decides to incompletely delete something from the DB in the future, it will be handled gracefully.

Sorry for taking so long.
