### ISSUE TITLE
Can't send quest links in chat.

### ISSUE THREAD

**Issue by barutari** [AeroScripts/QuestieDev#497]
When i link a quest in chat, it appears in yellow but when i press enter to send, may it be in group chat or whisper, nothing happens. (playing on Kronos 3)

**Comment by fxceptioN** [comment]
I'm having this same exact issue. When I had Questie 3.69 it worked fine, but never showed up as yellow in chat. Now that I've updated to 3.7 It doesn't show in chat at all. Kind of annoying. Any fix to this?

**Comment by Muehe** [comment]
[As I learned today](https://github.com/shagu/pfQuest/issues/49#issuecomment-382056897) This is a problem with Kronos not allowing coloured text in the chat.

As a workaround you can use `Ctrl+Click` instead of `Shift+Click` to paste normal text including the quest progression into the chat input field.

**Comment by fxceptioN** [comment]
Ctrl+Click doesn't work.

**Comment by Muehe** [comment]
@fxceptioN My bad, this is a feature of EQL3. You can get an updated version of it here: https://github.com/laytya/EQL3

**Comment by jongdetim** [comment]
not sure why this was closed. isn't it still an issue with questie?

**Comment by Muehe** [comment]
@jongdetim This was an issue about Questie 3.7 which is for WoW 1.12 servers (old classic/vanilla). If you have this problem with a current Questie version on Blizzard servers please open a new issue.
