### ISSUE TITLE
Quest Not Tracked: Find the Lost Guards

### ISSUE THREAD

**Issue by abennette32** [AeroScripts/QuestieDev#5]
Quest: http://www.wowhead.com/quest=37/find-the-lost-guards

No blips appear on the minimap, as the quest "cannot be tracked"

**Comment by AeroScripts** [comment]
Not even the quest finisher appears? As far as I can tell you turn in this quest to the hunk of meat object to get the next step. "Find the Lost Guards" points to "A half-eaten body" as it's finisher, so if it wasn't showing this could be a pretty fundamental bug. I'll look more into this shortly.

**Comment by abennette32** [comment]
Nope, no ticks on map from this quest at all.

**Comment by abennette32** [comment]
For the record, I am leveling as a human priest, doing every quest possible, so you'll get a bunch of bug reports from me

**Comment by AeroScripts** [comment]
Thanks again for making these, really helps with fixing things. Going to get my level 6 mage over to elwynn and see what's going on.

**Comment by abennette32** [comment]
No problem, my friend. I'll make them with every problem I find, regardless of the fact that I am unable to play very often.

**Comment by AeroScripts** [comment]
So I just picked up this quest on my mage and apparently it doesnt show anything, BUT if you click the quest it does (shows the proper quest finisher) because the quest finisher only shows if you have the quest selected. Going to make a change to make it always show the finisher if the quest is done or has no objectives, should fix this (and other similar quests)

**Comment by AeroScripts** [comment]
Fixed after d4fe57191e7efa1f9e668a8f5869f65021e3eaa3
