### ISSUE TITLE
Questie causing addons to reload repeatedly

### ISSUE THREAD

**Issue by buythedip591** [AeroScripts/QuestieDev#505]
I have used this release alongside 1.12 before without issue. However after a reinstall I am running into an issue where every 10 seconds or so Questie, along with my other addons, reload themselves over and over. This stops as soon as I remove Questie.

**Comment by Muehe** [comment]
Since there has been no feedback for a long time and it sounds like an installation error I'm going to close this issue. If you continue having problems please re-open the issue or contact us on Discord and provide more information on your general setup (OS, client location, Questie download source).
