### ISSUE TITLE
TBC "event" type quest data is potentially missing

### ISSUE THREAD

**Issue by AeroScripts** [AeroScripts/QuestieDev#532]
It's still using the original data pulled from QuestHelper which may or may not include TBC event locations. If it doesnt, the data should be pulled from QuestHelper again because its not in mangosdb anywhere that I know of, its all implemented in scripts

**Comment by VideoPlayerCode** [comment]
Hi again Aero! :-)

If you are going to pull QuestHelper data, be sure that you don't get any of the Wrath of the Lich King pre-release versions of QuestHelper. Their internal data has been edited to move quests to Northrend locations, and internally QH has some code to say "if we're still on TBC, re-calculate the positions at runtime".

So be sure that you get a version squarely within the TBC timespan, before WOTLK pre-release/test realm had begun.

Here's how you can check: Look in `upgrade.lua` for `QuestHelper_ConvertCoordsToWrath` and `QuestHelper_ConvertCoordsFromWrath`. If those functions exist, you know that you've found a too-new QuestHelper version.

PS: I know all this because I'm responsible for a deep backport of QuestHelper for WOTLK, backported for The Burning Crusade: https://github.com/VideoPlayerCode/QuestHelperTBC (v0.95, which is way better and has tons of bugfixes compared to the "v0.59" that most TBC users play with).

**Comment by BreakBB** [comment]
https://github.com/AeroScripts/QuestieDev/issues/504
