### ISSUE TITLE
Interface\Addons\!Questie\Modules\QuestieNotes.lua:397: attempt to index local 'questinfo' (a nil value)

### ISSUE THREAD

**Issue by ekztal** [AeroScripts/QuestieDev#535]
I get the following error on Questie 3.7.0 for one particular quest "Other Fish to Fry on Elysium:

"Interface\Addons\!Questie\Modules\QuestieNotes.lua:397: attempt to index local 'questinfo' (a nil value)"
I seem to get the error popup when I mouse over the corpse of a mob I need for the quest.

I ALSO get the following error when I mouse over this quest on the current quest list:
"Interface\Addons\!Questie\Modules\QuestieTracker.lua:236: attempt to index field ` ?' (a nil value)

**Comment by Muehe** [comment]
This bug may have been fixed by the [latest release](https://github.com/AeroScripts/QuestieDev/releases/tag/v3.7.1), please update and re-open the issue if the problem persists.

**Comment by skink-in-trees-shade** [comment]
Hey @Muehe, not sure if it's still relevant as you guys are pushing the next major version (gz!) but fwiw:

I was having the same problem on 3.7.1, same quest and same server as the OP. It turns out that the quest name has an extra whitespace at the end in the lua database (even in the current master). I don't know if it's a server bug or it's intended but removing the whitespace fixed this for me.

**Comment by Muehe** [comment]
@skink-in-trees-shade It's intended. The data came from network packages, so this is probably "blizzlike". Just some private servers getting it wrong. It works on cmangos based DBs, like Kronos. 

But we won't know for sure what the correct name is until somebody can test it on live 1.13 servers.
