### ISSUE TITLE
Quest Uncovering the Past

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#545]
Locations of the fragments are not shown on map.

Quest: https://www.wowhead.com/quest=299/uncovering-the-past

**Comment by AeroScripts** [comment]
I will look into this shortly. It's possible this is related to the API desync issue that we're working around (I think its actually a classic beta bug)

Anyway, if something is ever missing try /console reloadui because that fixes the desync issue and makes things show up.

Sometimes data really is missing, and that may be the case here, but until we fix that bug it can sometimes cause missing points

**Comment by BreakBB** [comment]
All items and objects are listed correctly
