### ISSUE TITLE
Use different marker for pickup / interact with world quests

### ISSUE THREAD

**Issue by christophrus** [AeroScripts/QuestieDev#557]
A pickup / interact with world quest can easiely been overlooked when there are other objectives in the same area.

Example: https://ibb.co/z7j0p71

In this case the "Furlbrow's Pocket Watch" from https://classic.wowhead.com/quest=64/the-forgotten-heirloom should use a different and outstanding marker to make it more present.

**Comment by AeroScripts** [comment]
This is definitely a problem I agree. Actually, we've been discussing giving "loot from a container" like the pocket watch have a different gear icon that is slightly larger, so it stands out a lot more visually

Also, once the tracker is implemented it will be easy to only show notes from quests you want to see, so that should help too

**Comment by BreakBB** [comment]
There are options to colorize the icons differently which helps on this issue and you can also focus a quest to fade out icons which don't belong to the focused quest.

Report back if this doesn't solve the issue.
