### ISSUE TITLE
Forbiden action while clicking on Party Frame

### ISSUE THREAD

**Issue by bandreetto** [AeroScripts/QuestieDev#639]
When trying to click a party frame (except player frame) while questie is enable will result in a popup saying: "Questie has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI." Sou you cant target party members through the raid frames UI while Questie is active.

# Steps to reproduce 
1. Enable raid frames for party in Interface Option > Raid Profiles > Use Raid-Style Party Frames.
2. Join a party.
3. With Questie active, click any frame but your frame.

**Comment by AeroScripts** [comment]
Very strange, ill test this today since beta is back up, but questie doesn't touch the unit frames at all, not sure why that would happen

**Comment by brewspy** [comment]
I encountered this too.

Restarting the game fixed it.

**Comment by AeroScripts** [comment]
@brewspy did this happen to you on 4.0.13 or newer? We recent pushed a change that should solve this. The fix may need to be applied in other places though

**Comment by brewspy** [comment]
> 
> 
> @brewspy did this happen to you on 4.0.13 or newer? We recent pushed a change that should solve this. The fix may need to be applied in other places though

I saw this before 4.0.13

**Comment by AeroScripts** [comment]
ahh. Well, it should be fixed now

The issue was, questie hooks GameTooltip to show the quest information when you mouse over mobs and objects in the game. The problem comes when an internal restricted blizzard UI tries to use GameTooltip, questie's hook code then runs to check if you moused over an NPC (which it isn't allowed to run at the time)

The solution is to always check "are we allowed to run code right now" inside the tooltip hook

**Comment by AeroScripts** [comment]
If anyone has this issue post 4.0.13 please let us know
