### ISSUE TITLE
Questie for 1.13 client quest issue: Crown of the Earth

### ISSUE THREAD

**Issue by hammerface** [AeroScripts/QuestieDev#640]
This is a quest line in NE starting zone where you need to go to various moonwells and fill vials. 

While doing these quests on August 11, 2019 Questie did not tell me any of the moonwell locations. 

Questie did correctly tell me where to turn in the quest once I'd completed the objective.

**Comment by Muehe** [comment]
Yeah the objectives of these quests are a bit tricky to get exact locations for. We will look into possible solutions once servers are back up.

**Comment by Muehe** [comment]
We currently put everything that is different from our DB into [corrections.lua](https://github.com/AeroScripts/QuestieDev/blob/master/Database/corrections.lua), since it allows us to do manual updates as well as extracting corrected data from our initial source (Cmangos).

Due to the nature of the quest and how our DB is structured it might be a bit tricky to correctly place the correction though. Plus we need to do it for all quests in the chain, since they all work the same.

**Comment by Muehe** [comment]
P.S.: The basic principle of these quests is they provide item A, which can be used around object B, to cast spell C, which creates item D and removes item A. The lookup is a bit tricky.

**Comment by BreakBB** [comment]
This should be fixed with 7548742
