### ISSUE TITLE
The Hunter's Path quest showing despite being completed

### ISSUE THREAD

**Issue by Painstormx** [AeroScripts/QuestieDev#653]
This quest is still showing on the map on 2 trainers in Darnassus, even though the quest has already been completed in Doolanar.

**Comment by BreakBB** [comment]
From the Wowhead data it looks like Blizzard changed some quests from vanilla to Classic.

[6072](https://classic.wowhead.com/quest=6072/the-hunters-path) is listed to start in IF.
[6073](https://classic.wowhead.com/quest=6073/the-hunters-path) is listed to start in SW.

In our data those quests both start on Teldrassil since those lead to Dolanaar.

My guess is that Blizzard changed the breadcrumb quests to start for each Hunter race in a capital city leading them to their starting place. Meaning nightelfes getting this quest in SW still have to go to Teldrassil.

Since multiple users stated those quests don't match with our data I think we should trust Wowhead on this, shouldn't we?

It will take some time though to go through all the 15 starting quests.

**Comment by BreakBB** [comment]
This has been tested and is fixed in the current version. If something similar comes up please create a new issue.
