### ISSUE TITLE
Webwood Egg Invalid itemdata on first render

### ISSUE THREAD

**Issue by Logonz** [AeroScripts/QuestieDev#69]
Webwood Egg Invalid itemdata on first render

**Comment by Schaka** [comment]
Probably a general issue where new quests are sometimes not picked up properly. In particular if a quest hasn't been cached (WDB folder), a reload is required for Questie to add it to the tracker (and draw frames for it) sometimes. 
This happens extremely rarely and will get fixed in a hotfix release for 2.0
