### ISSUE TITLE
Missing quest objective icon next to nameplate / mark quests as completed

### ISSUE THREAD

**Issue by Computerjul** [AeroScripts/QuestieDev#695]
Hello,

version: 4.0.11

on the german client i still cant see all quest objective icons next to the nameplate and the quest of and on the big map at all. Most of them show up but there are always few ones which dont show up. Also i cant mark specific quests as completed on the map or minimap because sometimes it shows a quest which i already completed or i just dont want to do it. Please also add more options for this if this is not a bug :) 

Huge thank you for keeping this up for us.

**Comment by Muehe** [comment]
The missing nameplates are due to missing localisation data in our DB.

The desync of map icons is also a known issue, sometimes it is fixed by using `/reload` in the chat.

Marking quests as hidden is on the roadmap.

Also 4.0.12 has been released today.

If you encounter any other problems feel free to open another issue or contact us on Discord.

**Comment by BreakBB** [comment]
Related to #860
