### ISSUE TITLE
Shaman Fire Totem quest

### ISSUE THREAD

**Issue by Versigh** [AeroScripts/QuestieDev#707]
I LOVE that this addon will show random quests all over the map that are available to pick up.  An issue I have had with this several times, however, is that it shows quests available that need a prerequisite before you can pick them up, even when i haven't done the prerequisite yet.  I have gone out of my way several times (which takes a while on foot!) to go to a quest only to find out I can't actually pick it up yet.  If there is a way to fix this to where those quests won't show on the map until all prerequisite quests have been done, that would be awesome!!  Otherwise, great addon guys, very helpful :)

**Comment by AeroScripts** [comment]
Really sorry about that, I find it equally frustrating and try to fix it whenever I encounter one ingame. There are some quests that do have incorrect requirement data in the DB. It's usually a pretty simple fix, once we know what quests are broken

These things didn't get noticed before generally because nostalrius for example used the same database. If you can try to post about the quests you encounter and we'll get them fixed. There's a few that have already been reported on here though, starting to fall a little behind because there have been some critical bugs that came up recently


We're also going to add back the "shift+click to hide quest" thing from the 1.12 version, so that should help a little bit (But please still try to report the quests so we can get the data fixed up)

**Comment by Versigh** [comment]
Alright thank you!!  The biggest one that bugged me yesterday was the Shaman fire totem quest (Fire Septa, I believe?), ran all the way out to finally find the quest giver only to realize he didn't actually have it - researched and found I had to do a quest before it.  I don't envy you guys, it has to be hard to keep track of all of this!!  You do a great job with your addon :)

**Comment by BreakBB** [comment]
With the latest changes to the subQuest system the quest "Fire Saptan" should only be shown if you're on the correct "Call of Fire" quest. Thanks for your report @Versigh and your kind words!
