### ISSUE TITLE
Desync still exists

### ISSUE THREAD

**Issue by MysticalOS** [AeroScripts/QuestieDev#719]
using .13 today i noticed a desync once, which admittedly, is MUCH less than how often it was before.

However I still had to reload in one case for a completed quest that was missing ? for turnin until I reloaded.

**Comment by AeroScripts** [comment]
Thanks for posting! Yeah, it seems to still be a thing, there was multiple things that can cause it, and those got lumped together since they both can be fixed with /reload

Now I think the only issue is with event timing (in QuestieEventHandler).
The part that was fixed was a bug with the frame pool. Sometimes frames would get added back to the pool multiple times, so notes would get "stolen" and moved around / removed (That's also why sometimes icons would appear semitransparent or in the wrong place, rarely)

**Comment by BreakBB** [comment]
Merging this with #860
