### ISSUE TITLE
Tome of Valor available even though I already have it

### ISSUE THREAD

**Issue by Ultroman** [AeroScripts/QuestieDev#742]
Screenshot should show all you need. I just downloaded the newest code from the branch. Picked up the quest yesterday, so before updating to the newest code. Had v4.0.12 BETA

![WoWScrnShot_090219_140450](https://user-images.githubusercontent.com/3922236/64113513-cec97180-cd8a-11e9-83a4-5ef064fc3440.jpg)

**Comment by AeroScripts** [comment]
Hmm, there are many copies of this quest with the same name (presumably for each race) It's likely that its showing the human version of the quest

I'll check the DB. We really gotta add a way to display quest IDs in the tooltips so it would be easier to figure out

**Comment by Ultroman** [comment]
Yeah. You could do that when holding Shift or something, like most other mods do with items.

**Comment by AeroScripts** [comment]
Good idea

**Comment by BreakBB** [comment]
The quest in the screenshot is most likely [this one (1793)](https://classic.wowhead.com/quest=1793/the-tome-of-valor) and since this is marked as repeatable it would explain the issue.

You get the Tome which starts [this quest (1649)](https://classic.wowhead.com/quest=1649/the-tome-of-valor) and leads to the quest you have in your questlog ([this one (1650)](https://classic.wowhead.com/quest=1650/the-tome-of-valor)).

**Comment by pat0007** [comment]
I am having the Tome of Divinity appear, but I have already completed it. v4.0.15 and have tried to /reload, but it's still there.

**Comment by BreakBB** [comment]
@pat0007 There are two existing issues for your problem at #703 and #720 . I already added a possible fix, but it seems to be not enough. Could you contact me on our Discord server about that to help debugging the quest?

**Comment by Ultroman** [comment]
I just noticed I also have the other marks for other parts of the quest line e.g. this one.
![WoWScrnShot_090419_203142](https://user-images.githubusercontent.com/3922236/64331619-66210580-cfd3-11e9-8b1f-04accf625204.jpg)
