### ISSUE TITLE
[45] Fiery Blaze Enchantments quest drop isn't on Scorched Guardians

### ISSUE THREAD

**Issue by Tyriar** [AeroScripts/QuestieDev#794]
![image](https://user-images.githubusercontent.com/2193314/64225342-da529080-ce8f-11e9-9f82-7f8413325f80.png)

According to wowhead, it only drops on Scalding Whelps https://classic.wowhead.com/item=4612/black-drakes-heart

**Comment by AeroScripts** [comment]
Hmm interesting. Just checked and there are comments on that wowhead page of people saying it dropped for them off scorched guardian, does questie currently list scalding whelps too?

Wowhead uses community sourced data which isnt always accurate for really low drop rate items. If we can confirm it doesn't drop ill remove it but those comments suggest it does also drop from scorched guardians

**Comment by Tyriar** [comment]
Yes questie says it drops off scalding whelps as well, I didn't think it was really possible at this point for wowhead to miss drops like this since it has so many data points (from thottbot/allakhazam back then)? The quest text also implies it's only on the whelps:

> but I can tell you it requires blood from a rare, still-beating black drake whelp's heart.

**Comment by AeroScripts** [comment]
For the classic db they pulled all new data from the beta foward using their tool afaik, its a fresh database (there have been some other issues)

We chan cahnge it but, theres definitely conflicting info online
"rldDominator on 2006/08/17 (Patch 1.11.2)
In keeping with the spirit of the quest, I decided to only kill the 43-45 elite Scorched Guardians. I was a 49 warrior and leveled to 50 during the quest. It dropped off the 64th dragonkin and took about an hour and a half."

"By jamesjiao on 2007/02/26 (Patch 2.0.8)
Got mine off the 3rd elite scorched guardian i killed"

There are also comments saying its not worth killing the guardians since the whelps are easier, might be worth removing anyway but im curious if it does drop

**Comment by Tyriar** [comment]
Oh if it's just based on beta data that would make sense then. Feel free to close, I got mine of a whelp fwiw

**Comment by AeroScripts** [comment]
If whelps are easier to kill / higher drop rate, maybe we should change it anyway

**Comment by drejjmit** [comment]
I got it from Scalding Whelps. 100% that i didn't kill any of those elites

**Comment by BreakBB** [comment]
Wowhead now lists both mobs for dropping the hearts, so our data is correct on this.
