### ISSUE TITLE
Rackmores Treasure in Desolace. Silver Key doesnt drop of naga

### ISSUE THREAD

**Issue by merasil** [AeroScripts/QuestieDev#819]
I dont saw any open issues regarding this quest. So here it is. At least yesterday the tooltip and map said that the silver key drops of nagas. Makuras werent mentioned anywhere.

Silver key = Makura
Gold key = Naga

https://classic.wowhead.com/quest=6161/claim-rackmores-treasure

questie master-branch version from 09/04/19 around 5pm. German WoW Client.

https://classic.wowhead.com/quest=6161/claim-rackmores-treasure

**Comment by AeroScripts** [comment]
Hmm, there may be something up with objective deteciton on this quest. It's possible it's not actually adding the silver key spawns and instead adding the golden key spawns, due to german client, or maybe just the quest in general

The data for the silver key in questie's DB is
```Lua
[15878]={"Rackmore's Silver Key",{6161},{11562,11563},{}},
```
which points to NPC 11562 and 11563, no nagas. The golden key lists nagas, so it has to be some logic issue

**Comment by slowcar** [comment]
I encountered the same issue today, also on the German client. Took me about an hour of killing nagas until i checked wowhead, classic droprates being what they are.
Third Makura dropped the key, then...

**Comment by BreakBB** [comment]
@slowcar Just to make sure: This happend with v4.1.1?

**Comment by slowcar** [comment]
> @slowcar Just to make sure: This happend with v4.1.1?
Yes. Sorry for not including the version.

**Comment by Rouilleur** [comment]
Hello, 
confirmed on French client

**Comment by BreakBB** [comment]
This is related to #1071
