### ISSUE TITLE
Battle for Darrowshire

### ISSUE THREAD

**Issue by Aviana** [AeroScripts/QuestieDev#857]
## Description
![Unbenannt](https://user-images.githubusercontent.com/425023/64471970-0869f600-d158-11e9-9fad-86249aadcdf7.png)

## Wowhead link
https://classic.wowhead.com/quest=5721/the-battle-of-darrowshire

## Screenshots
See above

## Questie version
4.0.17

**Comment by BreakBB** [comment]
I investigated this quest a little bit and I think the problem is that the quest goal is to "Accept Redpath's Forgiveness". You do this by simply talking to the NPC, but this is an interaction which we can't track afaik.

The error itself is because of a missing spawn entry of [Joseph Redpath](https://classic.wowhead.com/npc=10936/joseph-redpath) which we can't really add because he will spawn where ever [Redpath the Corrupted](https://classic.wowhead.com/npc=10938/redpath-the-corrupted) will be defeated.

The only solution I can think of is using the defeat of the corrupted NPC as completion marker.
