### ISSUE TITLE
Senir's Observation

### ISSUE THREAD

**Issue by S1m8aa** [AeroScripts/QuestieDev#881]
## Description
Questie shows Senir's Observation quest in Coldridge Valley as available to me even tough it isn't. In this quest series you have to deliver a letter from Grelin Whitebeard to Mountaineer Thalos and onwards to Senir Whitebeard. I haven't completed it and it's probably unobtainable for me because I already spoke to Senir Whitebeard before I got to Coldridge Valley.

## Wowhead link
https://classic.wowhead.com/quest=282/senirs-observations
https://classic.wowhead.com/quest=420/senirs-observations

## Screenshots
![Screen shot](https://user-images.githubusercontent.com/55045451/64485317-be504580-d227-11e9-8bbe-9f5cf5785564.jpg)

## Questie version
v4.0.18

**Comment by AeroScripts** [comment]
Hmm thanks for the report, sounds like a bad ExclusiveGroup(breadcrumb) data, ill check the DB

Oh also I try to remind everyone because it was only recently added but, you can now shift+click the available quests to hide them for the time being (They can also be hidden or unhidden via the quest search UI)

**Comment by hopdenakker** [comment]
If you've completed the quest Frostmane Hold (https://classic.wowhead.com/quest=287/frostmane-hold) this quest should be marked as unavailable.
