### ISSUE TITLE
[50] The Mystery of Morrowgrain

### ISSUE THREAD

**Issue by drejjmit** [AeroScripts/QuestieDev#885]
## Description
Not offered by Quintis Jonespyre.
Wowhead got some info about required prequests.

## Wowhead link
https://classic.wowhead.com/quest=3791/the-mystery-of-morrowgrain

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/64492106-b2d53c80-d270-11e9-99b6-02a5ec12b16d.png)

## Questie version
v4.0.17

**Comment by Daniel-Fischer** [comment]
In order to get **The Mystery of Morrowgrain** it requires the completion of [this quest](https://classic.wowhead.com/quest=3787/jonespyres-request) which requires the completion of [Morrowgrain Research](https://classic.wowhead.com/quest=3785/morrowgrain-research). This was also shown incorrectly for me on Questie v4.0.15.

**Comment by BreakBB** [comment]
Actually this quest requires you to *either* grab Jonespyre's Request for [Stormwind](https://classic.wowhead.com/quest=3787/jonespyres-request) or from [Feathermoon Stronghold](https://classic.wowhead.com/quest=3788/jonespyres-request).
Questie can't handle such cases yet, so we list only one quest of the possible preQuests.

I've added the preQuest from Feathermoon Stronghold for now with 6107cc92b2d5aa232a4dec7df3bf6a9c9e1f728f

So The Mystery of Morrowgrain should work fine

**Comment by BreakBB** [comment]
This has been fixed with 4a1fcabf45c1f5b6be65291fb92e5ddff2370e30 and will be included in the upcoming v4.1.3
