### ISSUE TITLE
Questie stops tracking after String of the Scorpid hand in

### ISSUE THREAD

**Issue by hwwilliams** [AeroScripts/QuestieDev#894]
## Description
Two issues I've found while leveling an Orc Warlock

1. I was able to pick up and turn in the first four quests normally following Questie but once it asks to hand in the "Tained Parchment" quest I also see a "Quests Missing: 1234567890" header.

2. When I go to turn in "Galgar's Cactus Apple Surprise", "Sting of the Scorpid", and "Lazy Peons"
it never points me to the "Lazy Peon" quest giver once "Sting of the Scorpid" has been turned in. It instead has the arrow pointing to the Burning Blade Medallion quest giver and once you walk up to it the Questie arrow disappears and no longer tracks any quests going forward.

## Wowhead link
https://classic.wowhead.com/quest=794/burning-blade-medallion

## Questie version
v4.0.18

**Comment by BreakBB** [comment]
Your first issue has nothing to do with Questie but is a problem in the (Azeroth Auto Pilot) AAP addon.

For your second issue it sounds more like AAP than Questie, since you have to manually set the arrow for it to point yout to quests. Please check AAP and report back when you have more detailed information on this. A screenshot might help as well!

**Comment by hwwilliams** [comment]
You are correct, that's my mistake. I'll close this out.
