### ISSUE TITLE
Quest Not in Database

### ISSUE THREAD

**Issue by Oxycleaned** [AeroScripts/QuestieDev#978]
Quest: Parts of the Swarm is not being tracked by the addon.

**Comment by BreakBB** [comment]
Thanks for the report. It would be great if you could follow the issue template next time.

**Comment by BreakBB** [comment]
I've had a look at our data and couldn't find any issue. Could you explain a bit more what your issue was with this quest?

**Comment by Oxycleaned** [comment]
The quest “Parts of the Swarm” is started from the item “Cracked Silithid
Carapace” which drops off Silthids in Thousand Needles if you have
completed part 2 of the chain “The Swarm Grows.”

After starting the quest none of the Questie data loaded for the quest;
map/minimap location, or indication on the mob tooltip (0/5 Silithid Talon
for instance.)

Looking on Classicdb it says that the “Cracked Silithid Carapace” drops off
Silithids in Tanaris and not Thousand Needles. Maybe it could be the
reference database that’s wrong I’m not sure.

I’m not using any other quest related addons, I can send you the list of
other addons I’m using when I get home if you want.

**Comment by BreakBB** [comment]
First of all: You should use http://classic.wowhead.com instead of classicDB, since you Classic is different to vanilla in many ways.

[Cracked Silithid Carapace](https://classic.wowhead.com/item=5877/cracked-silithid-carapace) is listed to drop off the Silithids in Thousand Needles and all the items required for this quest are listed in our data as well.
And so are the mobs which drop those items.

Which version of Questie were you using?

**Comment by BreakBB** [comment]
@Oxycleaned Please let me know if this isn't fixed with v4.1.2 https://github.com/AeroScripts/QuestieDev/releases/tag/v4.1.2
