### ISSUE TITLE
Questie's Quest log can't move after many attempts

### ISSUE THREAD

**Issue by weedpuff420** [AeroScripts/QuestieDev#981]
I'm using Questie 4.0.15v Beta and I'm unable to move my quest log even on the updated questies that you have posted. The more updated questies don't show the questie button so I can't toggle the options nor can I open the menu through /questie. 4.0.15v Beta is the that's working for me. I done all the ctrl+ left clicks and shift+left clicks and nothing because I'm not a noob or stupid.

I'll wait for your reply.

**Comment by BreakBB** [comment]
Sorry for the late reply. You should grab v4.0.18 or wait a little bit for 4.1 and install that version. The "quest log" window is not modified by Questie so I am not sure what your issue is.

When updating you have to make sure to restart WoW. If you can't even use `/questie` it sounds like a broken installation. Have a look at the wiki for an installation guide.

**Comment by weedpuff420** [comment]
I've followed the installation guide to a T and I'm having a problem with new updated questies. The 4.0.15v is the only one working and that shows on the addon option during character selection. All the other questies are not detected. How do I make it so my Quest log can move on 4.0.15v?

**Comment by weedpuff420** [comment]
WOO! The new questie 4.1.0v Works and I can move the log! Good job! Issue resolves!

Thanks! JEA!

**Comment by BreakBB** [comment]
Glad to hear you can move your questlog. I have to be honest and say that this is no feature of Questie, but I guess some conflict with another addon has been resolved. Thanks for coming back to report :+1:
